### ISSUE TITLE
Initialization issues when doing matrix multiplication

### ISSUE THREAD

**Issue by bart1** [stan-dev/rstan#579] opened 2018-11-02 09:14 UTC
I do encounter issues when doing a matrix multiplication, the
initialization fails for some chains. Initially a full version of this
model seemed to be working without any issues (I tried to reduce the
example as much as possible, it is part of a R package, I’m developing).
Recently I have run into this issue. The `movementMatrix`, is a
integrated cubic smooth (I tried to reduce it further but then the error
disappears). The error depends on the reject statement of the model.

I think there are 3 main issues here:

  - First the error message `Initialization between (-2, 2) failed
    after 100 attempts.` is rather uninformative (maybe this relates to
    \#577).
  - It is strange that 4 chains initiated with with fixed init values 1
    fails while others work, that seems inconsistent. I would expect all
    to fail or work (not this failure depends on the seed and thus maybe
    relates to random values). It seems this failure occurs before the
    parameter block is fully evaluated (derived from the print
    statements), for other chains the first evaluation is with the init
    values and thus should be valid.
  - The matrix multiplication in combination with negative values
    somehow seem to cause the issue. This should really not be a problem
    since all values for the init matrix multiplication are positive
    when calculated in R.

File to reproduce: [movementMatrix.R.txt](https://github.com/stan-dev/rstan/files/2541770/movementMatrix.R.txt)

``` r
model<-'data {
  int<lower=2> N;
  int<lower=1> NparMovement;
  matrix[N,NparMovement] movementMatrix;
}
parameters {
  vector[NparMovement] movementPar;
}
transformed parameters {
  vector[N] sigmaEstimatesSquare;
  print("Params to transform");
  print(movementPar);
  sigmaEstimatesSquare= movementMatrix * movementPar;
  print(min(sigmaEstimatesSquare));
  if(min(sigmaEstimatesSquare)<0){
    print("rejecting");
    reject("Negative sigma^2 values");
  }
}
model {
  target += 234;
}'
source('movementMatrix.R.txt')


N <- nrow(movementMatrix)
NparMovement <- ncol(movementMatrix)

require(rstan)
```

    ## Loading required package: rstan

    ## Loading required package: ggplot2

    ## Loading required package: StanHeaders

    ## rstan (Version 2.18.1, GitRev: 2e1f913d3ca3)

    ## For execution on a local, multicore CPU with excess RAM we recommend calling
    ## options(mc.cores = parallel::detectCores()).
    ## To avoid recompilation of unchanged Stan programs, we recommend calling
    ## rstan_options(auto_write = TRUE)

``` r
init<- rep(1, NparMovement)
i<-list(list(movementPar=init))[rep(1,4)]
set.seed(34654)
# the matrix multiplication is positive
range(movementMatrix%*%init)
```

    ## [1] 1.157406e-05 1.157408e-05

``` r
# Chain 2 fails
jj<-stan(model_code = model, data=list(N=N, NparMovement=NparMovement,movementMatrix=movementMatrix), 
         chains = 4, cores=4, iter = 2, warmup = 1, init=i)
```

    ## In file included from file5ddd10356cfc.cpp:8:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/src/stan/model/model_header.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/rev/mat.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/rev/core.hpp:14:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/rev/core/matrix_vari.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/rev/mat/fun/Eigen_NumTraits.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/prim/mat/fun/Eigen.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/RcppEigen/include/Eigen/Dense:1:
    ## In file included from /usr/local/lib/R/3.5/site-library/RcppEigen/include/Eigen/Core:531:
    ## /usr/local/lib/R/3.5/site-library/RcppEigen/include/Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    ##     #pragma clang diagnostic pop
    ##                              ^
    ........
    ## In file included from file5ddd10356cfc.cpp:8:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/src/stan/model/model_header.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math.hpp:4:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/rev/mat.hpp:12:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/prim/mat.hpp:96:
    ## In file included from /usr/local/lib/R/3.5/site-library/StanHeaders/include/stan/math/prim/mat/fun/csr_extract_u.hpp:6:
    ## In file included from /usr/local/lib/R/3.5/site-library/RcppEigen/include/Eigen/Sparse:33:
    ## In file included from /usr/local/lib/R/3.5/site-library/RcppEigen/include/Eigen/IterativeLinearSolvers:46:
    ## /usr/local/lib/R/3.5/site-library/RcppEigen/include/Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    ##     #pragma clang diagnostic pop
    ##                              ^
    ## 13 warnings generated.
    starting worker pid=24219 on localhost:11966 at 10:04:26.968
    starting worker pid=24229 on localhost:11966 at 10:04:27.131
    starting worker pid=24239 on localhost:11966 at 10:04:27.293
    starting worker pid=24249 on localhost:11966 at 10:04:27.454
    
    SAMPLING FOR MODEL '7091d00e3a0610004dfd822f880dffe3' NOW (CHAIN 1).
    Chain 1: Params to transform
    [1,1,1,1,1,1,1,1,1]
    1.15741e-05
    .....
    Chain 1:  Elapsed Time: 0.00026 seconds (Warm-up)
    Chain 1:                0.00024 seconds (Sampling)
    Chain 1:                0.0005 seconds (Total)
    
    SAMPLING FOR MODEL '7091d00e3a0610004dfd822f880dffe3' NOW (CHAIN 2).
    Chain 2: Initialization between (-2, 2) failed after 100 attempts. 
    [1] "Error in sampler$call_sampler(args_list[[i]]) : Initialization failed."
    error occurred during calling the sampler; sampling not done
    
    SAMPLING FOR MODEL '7091d00e3a0610004dfd822f880dffe3' NOW (CHAIN 3).
    Chain 3: Params to transform
    [1,1,1,1,1,1,1,1,1]
    1.15741e-05
    
    Chain 3: Params to transform
    [1,1,1,1,1,1,1,1,1]
    1.15741e-05
    
    Chain 3: Gradient evaluation took 7.8e-05 seconds
    Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.78 seconds.
    .......
    Chain 4:  Elapsed Time: 0.000437 seconds (Warm-up)
    Chain 4:                0.000182 seconds (Sampling)
    Chain 4:                0.000619 seconds (Total)
    ## Warning in .local(object, ...): some chains had errors; consider specifying
    ## chains = 1 to debug

    ## here are whatever error messages were returned

    ## [[1]]
    ## Stan model '7091d00e3a0610004dfd822f880dffe3' does not contain samples.

    ## Warning: There were 3 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
    ## http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup

    ## Warning: Examine the pairs() plot to diagnose sampling problems

``` r
sessionInfo()
```

    ## R version 3.5.1 (2018-07-02)
    ## Platform: x86_64-apple-darwin15.6.0 (64-bit)
    ## Running under: OS X El Capitan 10.11.6
    ## 
    ## Matrix products: default
    ## BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    ## LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    ## 
    ## locale:
    ## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] rstan_2.18.1       StanHeaders_2.18.0 ggplot2_3.1.0     
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.19       pillar_1.3.0       compiler_3.5.1    
    ##  [4] plyr_1.8.4         bindr_0.1.1        prettyunits_1.0.2 
    ##  [7] base64enc_0.1-3    tools_3.5.1        digest_0.6.18     
    ## [10] pkgbuild_1.0.2     evaluate_0.12      tibble_1.4.2      
    ## [13] gtable_0.2.0       pkgconfig_2.0.2    rlang_0.3.0.1     
    ## [16] cli_1.0.1          parallel_3.5.1     yaml_2.2.0        
    ## [19] loo_2.0.0          bindrcpp_0.2.2     gridExtra_2.3     
    ## [22] withr_2.1.2        dplyr_0.7.7        stringr_1.3.1     
    ## [25] knitr_1.20         stats4_3.5.1       rprojroot_1.3-2   
    ## [28] grid_3.5.1         tidyselect_0.2.5   glue_1.3.0        
    ## [31] inline_0.3.15      R6_2.3.0           processx_3.2.0    
    ## [34] rmarkdown_1.10     callr_3.0.0        purrr_0.2.5       
    ## [37] magrittr_1.5       codetools_0.2-15   matrixStats_0.54.0
    ## [40] ps_1.2.0           backports_1.1.2    scales_1.0.0      
    ## [43] htmltools_0.3.6    assertthat_0.2.0   colorspace_1.3-2  
    ## [46] stringi_1.2.4      lazyeval_0.2.1     munsell_0.5.0     
    ## [49] crayon_1.3.4

**Comment by slaweku** [comment] 2018-11-03 20:47
Hi,
I also believe that something wrong happened to initialization in rstan 2.18. My models used to work, now half of them fail on initialization, and due to #577 I do not have even chance to see what is happening.

**Comment by bart1** [comment] 2018-11-05 11:52
For the record I reproduced the problem on a linux machine, although a different chain fails

```R
R version 3.4.3 (2017-11-30)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: SUSE Linux Enterprise Server 12 SP3

Matrix products: default
BLAS/LAPACK: /.../intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.UTF8        LC_COLLATE=en_US.UTF8    
 [5] LC_MONETARY=en_US.UTF8    LC_MESSAGES=en_US.UTF8   
 [7] LC_PAPER=en_US.UTF8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.UTF8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.18.1       StanHeaders_2.18.0 ggplot2_3.0.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19       pillar_1.3.0       compiler_3.4.3     plyr_1.8.4        
 [5] bindr_0.1.1        prettyunits_1.0.2  base64enc_0.1-3    tools_3.4.3       
 [9] pkgbuild_1.0.2     tibble_1.4.2       gtable_0.2.0       pkgconfig_2.0.2   
[13] rlang_0.3.0        cli_1.0.1          parallel_3.4.3     loo_2.0.0         
[17] bindrcpp_0.2.2     gridExtra_2.3      withr_2.1.2        dplyr_0.7.7       
[21] stats4_3.4.3       grid_3.4.3         tidyselect_0.2.5   glue_1.3.0        
[25] inline_0.3.15      R6_2.3.0           processx_3.2.0     callr_3.0.0       
[29] purrr_0.2.5        magrittr_1.5       scales_1.0.0       ps_1.2.0          
[33] codetools_0.2-15   matrixStats_0.54.0 assertthat_0.2.0   colorspace_1.3-2  
[37] lazyeval_0.2.1     munsell_0.5.0      crayon_1.3.4      

```

**Comment by bart1** [comment] 2018-11-05 11:59
This is the script to quickly reproduce: [issue.R.txt](https://github.com/stan-dev/rstan/files/2548257/issue.R.txt)

**Comment by bob-carpenter** [comment] 2018-11-05 16:31
I think the problem is that there's nothing in the constraints on the parameters that guarantee the condition being tested for rejection.  To simplify to just the relevant bits:

```
data {
  int<lower=2> N;
  int<lower=1> NparMovement;
  matrix[N,NparMovement] movementMatrix;
}
parameters {
  vector[NparMovement] movementPar;
}
transformed parameters {
  vector[N] sigmaEstimatesSquare = movementMatrix * movementPar;
  if(min(sigmaEstimatesSquare)<0) reject("...");
}
```

Nothing is constraining `movementPar` to ensure that `movementMatrix * movementPar` remains positive.  I dont see where the `Square` comes from---it seems to imply positivity, but I don't see the squaring anywhere.

**Comment by bart1** [comment] 2018-11-05 20:52
Thank you for having a look a this. Your right that nothing in the parameter settings ensures positive values. I'm trying to model variances, thus `sigmaEstimatesSquare` needs to be positive. The square in the naming just reflect that these are the variances. Because the specification of the `movementMatrix` (a model matrix) is flexible It is hard a-priori set parameter ranges. Also the ranges of the parameters are interdependent. That is why I used this setup of rejecting if there are negative values after the matrix multiplication. As said before this used to work without a problem before and produce good results. I have also explored transforming `sigmaEstimatesSquare` to ensure positivity but I'm less keen on that approach, given it makes it harder to interpret the parameter estimates.

Similarly once the initialization has been passed this works works without a problem.

**Comment by bob-carpenter** [comment] 2018-11-06 01:54
Stan wasn't designed to act as an efficient rejection sampler.  If you have parameter values that satisfy the declared parameter constraints, Stan assumes any legal value has support (finite log density) in the model.  

I don't believe anything changed between 2.17 and 2.18 as far as initialization went (other than RStan dropping the error messages).  

One thing such a model misses is normalization.  This is only a big deal if the normalization depends on parameters.  For example, it's OK to do this:

```
real<lower = 0> alpha;
alpha ~ normal(0, 1);  // normalization factor 1/2 is constant
```

because the normalization on the log scale for the half-normal implied here is -log(0.5), which is constant.  This is not the case for

```
real<lower = 0> alpha;
alpha ~ normal(mu, sigma);  // WRONG!  now normalization depends on mu, sigma
```

Now the normalization depends on `mu` and `sigma` and is not constant and thus must be included in the log density.  This can be done for simple truncation as

```
alpha ~ normal(mu, sigma) T[0, ];
```

which is just shorthand for

```
alpha ~ normal(mu, sigma);
target += -normal_lcdf(0 | mu, sigma);  
```

In your case, given that the constraint depends on a data matrix, I'm not 100% sure if you need to normalize or not.  I'd need to work it out in a simple case with only a couple dimensions to see.  Did you simulate fake data and check the posterior interval coverage over multiple runs?  That'll make sure everything's working properly.

**Comment by bart1** [comment] 2018-11-06 15:46
Thank you for the feedback. 

I do not want to do rejection sampling (where from a random set of samples some are retained), but there are indeed parameters combinations that invalid. As said this was solved until now by rejecting these combination. 

The experience up to now was that this approach of rejecting parameter combinations worked well. After initialization the chains converged on parameter values, maybe once in a while rejecting a parameter combination. When I simulated a datasets for this model (independently in R) I was able to reproduce parameters, both for models that include smooths and models with other parameters. 

I'm not really seeing how I could realistically specify constrains on the parameters when they (the constrains) are dependent on other parameter values. Maybe I'm missing something here.

The full model I want to approach is probably unnecessarily complex but I can produce a more complete example with simulated data if that helps. However I do not know it this would produce the same errors. 

Independent of these model specification considerations, I still think it is strange that the initialization fails given some chains work while others don't and they are initialized in the same way. It also seems this failure is independent of starting values, I at least still see failing chains if I change the initial value from `1` to `1000` which should definetly produce positive values during initialization.

**Comment by bart1** [comment] 2018-11-06 20:13
For completeness I have made a quick mock up model, and actually the initialization problem reproduces (note that the nice thing here is that the variances are additive ):

```r
require(rstan)
require(mgcv)
rstan_options(auto_write = TRUE)
modelMat<-cSplineDes(((0:3000)/100)%%1,c(0:4)/4)
set.seed(245)
modelMat<-cbind(runif(nrow(modelMat),-1),runif(nrow(modelMat),.2),modelMat)
pars<-c(1,9,9,7,-2.5,5)
stopifnot(0<min(modelMat %*%pars))
data<-rnorm(nrow(modelMat),0, sd=sqrt(modelMat %*% pars))
plot(data);lines(modelMat %*% pars)
model<-'
data {
int<lower=2> N;
int<lower=1> Npar;
matrix[N,Npar] modelMat;
vector[N] dat;
}
parameters {
vector[Npar] pars;
}
transformed parameters {
vector[N] sigmaEstimatesSquare = modelMat * pars;
if(min(sigmaEstimatesSquare)<0)
{print("rejecting");
reject("...");}
}
model {
dat ~ normal(0,sqrt(sigmaEstimatesSquare));
}
'
# Functioning example
aa<-stan(seed=9249,cores=4,model_code = model, 
         data = list(dat=data, modelMat=modelMat, N=length(data), Npar=ncol(modelMat)), 
         init=list(list(pars=rep(1,6)))[rep(1,4)], iter=500, warmup = 100)
stan_trace(aa, pars='pars', inc_warmup = T)

# Failing example (Chain 1 fails)
aa<-stan(seed=949,cores=4,model_code = model, 
         data = list(dat=data, modelMat=modelMat, N=length(data), Npar=ncol(modelMat)), 
         init=list(list(pars=rep(1,6)))[rep(1,4)], iter=500, warmup = 100)
stan_trace(aa, pars='pars', inc_warmup = T)
```

**Comment by bob-carpenter** [comment] 2018-11-06 21:09
> On Nov 6, 2018, at 10:46 AM, bart1 <notifications@github.com> wrote:
> 
> Thank you for the feed back.
> 
> I do not want to do rejection sampling (where from a random set of samples some are retained), but there are indeed parameters combinations that invalid. As said this was solved until now by rejecting these combination.

That's what happens when Stan rejects because not all parameters are in support.    It can actually cause the whole process to lock up if the proposals can't find things in support.

> The experience up to now was that this approach of rejecting parameter combinations worked well. After initialization the chains converged on parameter values, maybe once in a while rejecting a parameter combination. When I simulated a datasets for this model (independently in R) I was able to reproduce parameters, both for models that include smooths and models with other parameters.

If you could reproduce them by simulating from the priors and get
appropriate coverage, then the Jacobian's probably constant.  It's hard
to get this right if the model's off, especially if you run it for
a few hundred simulations.

> I'm not really seeing how I could realistically specify constrains on the parameters when they (the constrains) are dependent on other parameter values. Maybe I'm missing something here.

It will wind up being some kind of quadratic (or in your case
cubic) set of inequalities.  Certainly a pain to deal with, but
not impossible.  It's like what we do to constrain matrices to
be positive definite (though that's actually easier with Cholesky
factor representations).

> 
> The full model I want to approach is probably unnecessarily complex but I can produce a more complete example with simulated data if that helps. However I do not know it this would produce the same errors.

I don't understand what your model's doing.  I'm just trying
to address the Stan questions.  

> 
> Independent of these model specification considerations, I still think it is strange that the initialization fails given some chains work while others don't and they are initialized in the same way. It also seems this failure is independent of starting values, I at least still see failing chains if I change the initial value from 1 to 1000 which should definetly produce positive values during initialization.

You can add debug print statements to try to track where you get
a rejection, infinite, or not-a-number result.  Overflow can cause problems,
too.  Floating point's just a terrible thing to work with.

Is there any way to initialize with realistic values?

**Comment by bob-carpenter** [comment] 2018-11-06 21:16
Pulling out and formatting the simplified model that gets failures,

```
data {
  int<lower=2> N;
  int<lower=1> Npar;
  matrix[N, Npar] modelMat;
  vector[N] dat;
}
parameters {
  vector[Npar] pars;
}
transformed parameters {
  vector[N] sigmaEstimatesSquare = modelMat * pars;
  if (min(sigmaEstimatesSquare)<0) {
    print("rejecting");
    reject("...");
  }
}
model {
  dat ~ normal(0, sqrt(sigmaEstimatesSquare));
}
```

The problem (for Stan) remains that nothing in the declaration of `pars` guarantees that `min(modelMat * pars) > 0` for all possibe  values of `pars`.  Stan's just not designed to work in this situation.  It reduces to a kind of random walk rejection sampling that our adaptation is not designed to handle.

I see what the model's defining, but I don't understand the purpose of `modelMat` and `pars`.

**Comment by bob-carpenter** [comment] 2018-11-06 22:33
The constraint's not actually so bad when you write it out.  Requiring `min(A * b) > 0` for `A` a known (`K x K`) matrix and `b` a `K`-vector parameter is the same as requiring

```
y[1] * A[1, 1] + ... + y[K] * A[1, K] > 0
...
y[1] * A[K, 1] + ... + y[k] * A[K, K] > 0
```

Rearranging the first row yields the constraint.

```
y[K] > (y[1] * A[1, 1] + ... y[K - 1] * A[1, K - 1]) / A[1, K]
```

This has to hold for all rows `k in 1:K`.  Rewriting in matrix notation, this requires for `k in 1:K`, that

```
y[K] > (A[k, 1:K-1] * y[1:K - 1]) / A[k, K]
```

So you take the max of the right-hand side over `k in 1:K` and make that the lower-bound on `y[K]`

```
functions {
  real lb_functions(matrix A, vector y) {
    vector[rows(y)] z;
    for (k in 1:K - 1)
      z[k] = ((A[k, 1:K-1] * y) / A[k, K])[1];  // result is a vector, extract single element
   return max(z);
 }
}

parameters {
  vector[K - 1] y_prefix;
  real<lower = lb_fun(A, y_prefix)> yK;
transformed parameters {
  vector[K] y = append_row(y_prefix, yK);
```

You should check my algebra and coding, but something like this should work.  Defining it this way it's clear there's no additional Jacobians required and everything should normalize properly. 

Sorry this is all so complicated, but it's an involved implicit constraint.

**Comment by bart1** [comment] 2018-11-08 21:04
Meanwhile I got quite a bit further with this. With the input I managed to come up with a functional model with some constrains (I moved this to the first column given that is most likely the intercept). For future reference there is an functioning example below. It looks very much like the example above, except I build in functionality to add a constant  to the first column. This makes sure that even in case this column contains negative and positive values still constrains can be calculated, while the right parameters are estimated. 

During initialization i do get messages about the contains failing.
```
Chain 4: Rejecting initial value:
Chain 4:   Error evaluating the log probability at the initial value.
Chain 4: lub_constrain: lb is 9.23608e-05, but must be less than -0.000231881
```

The one problem I have not found a solution to yet is how to deal with cases where the column that is used for the constrain contains 0 values, in that cases the constraint in that row does not influence the estimate and thus does not work. One solution is to add a very small value to this column as a whole, this seems solve this but ever so slightly influences parameter estimations at least theoretically. 

Debugging this is hindered by the fact that it does not seem possible to `print` from functions called during the initialization. This is a small example (I would expect `hello world` to be printed besides the error message about the interval, but this does not happen)(is it desirable to make this into a separate issue?):

```r
require(rstan)
mod <- "
functions {
  real lb_fun(real a)
  {
    print(\"hello world\");
    return(10);
  }
}
parameters{
  real <lower=-1, upper=1> b;
  real <lower=lb_fun(b), upper=9> d;
}
"
aa<-stan(model_code = mod)
```


The mostly functional model
```r
require(rstan)
require(mgcv)
rstan_options(auto_write = TRUE)
modelMat<-cSplineDes(((0:9000)/5000)%%1,c(0:5)/5)
set.seed(326)
modelMat<-cbind(runif(nrow(modelMat),-.8,.2),modelMat)
pars<-c(2,9,7,6,8,1)
stopifnot(0<min(modelMat %*%pars))
data<-rnorm(nrow(modelMat),0, sd=sqrt(modelMat %*% pars))
plot(data);lines(sqrt(modelMat %*% pars), col='red')

model2<-'
functions {
  vector lb_funrange2(matrix mm, vector y, real raise) {
    vector[rows(mm)] w=-((mm[, 2:cols(mm)] * y)./( mm[,1]-raise)); 
    real mmin=1 ./min(1 ./w);
    real mmax=1 ./max(1 ./w);
    vector[2] aa=[mmin, mmax]\';
    if(0<=min(mm[,1]-raise))
    {
      return([max(w), positive_infinity()]);
    }
    if(0>max(mm[,1]-raise))
    {
      return([negative_infinity(), min(w)]);
    }
    if(0>min((mm[, 2:cols(mm)] * y)-raise*(mmin+(mmax-mmin)/2)+mm[,1]*(mmin+(mmax-mmin)/2)))
    {
      aa=[mmax, mmin]\';
    }
    return(aa);
  }
}
data {
  int<lower=2> N;
  int<lower=1> Npar;
  matrix[N,Npar] modelMat;
  vector[N] dat;
}
transformed data{
  real<lower=0> raise;
  matrix[N,Npar] modelMatRaised=modelMat;
  if(min(modelMat[,1]) <= 0)
  {
    raise=fabs(min(modelMat[,1]))+1;
  }else{
    raise=0;
  }
  modelMatRaised[,1]=modelMat[,1]+raise;
}
parameters {
  vector[Npar - 1] y_suffix;
  real<lower = lb_funrange2(modelMatRaised, y_suffix, raise)[1], upper=lb_funrange2(modelMatRaised, y_suffix, raise)[2]> y1;
}
transformed parameters {
  vector[Npar] pars = append_row(y1, y_suffix);
  vector[N] sigmaEstimatesSquare = (modelMatRaised * pars)- raise*y1;// substract raise *y1 here to get back in original param space
  if(min(sigmaEstimatesSquare)<0)
  { 
    reject("...");
  }
}
model { 
  dat ~ normal(0,sqrt(sigmaEstimatesSquare));
}
'
ab<-stan(seed=949,cores=4, chains = 4,model_code = model2, 
         data = list(dat=data, modelMat=modelMat, N=length(data), Npar=ncol(modelMat)), 
         init=list(list(y1=2, y_suffix=pars[-1]))[rep(1,4)], 
         iter=2000, warmup = 1000)
stan_trace(ab, par='pars')
pars
```

**Comment by bgoodri** [comment] 2018-11-08 21:18
try with rstan 2.18.2 from CRAN to see initialization messages

**Comment by bart1** [comment] 2018-11-08 21:27
@bgoodri 
This was running with rstan 2.18.2, I also do get the initialization messages, I just lack the printing messages (the `hello world` in the example above). I use these frequently for primitive debugging

**Comment by bgoodri** [comment] 2018-11-08 21:42
Yeah, I think the exception for violating the constraint kicks in before
the buffered print statement gets flushed.

**Comment by bob-carpenter** [comment] 2018-11-09 22:59
The easiest solution is just going to be use exp(...) to make sure everthing's positive.

But you're right, if there's a zero entry, then my approach won't work.  The constraints may also introduce difficult geometry, whereas the exp() should be very robust.  It's what we use for link functions, in say, Poisson regressions, where the parameters have to be positive.

We want to keep the issue tracker focused on issues, so I'm going to close this issue and ask that this conversation be moved to the [Stan forums](https://discourse.mc-stan.org).   Thanks for your patience.

**Closed as completed by bob-carpenter** 2018-11-09 22:59 UTC
