### ISSUE TITLE
Error with "RStan Getting Started" code

### ISSUE THREAD

**Issue by ivan-paleo** [stan-dev/rstan#781] opened 2020-06-24 10:11 UTC
I am very very new to RStan (and Stan in general).
I have followed these steps to install RStan: https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started
All went smoothly without errors (I did not run the "Configuration of the C++ Toolchain" part).

But when I run this line of code:
```fit <- stan(file = 'schools.stan', data = schools_dat)```
I get the following error:
"Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.1/bin/x64/R CMD SHLIB file42d83c2e3b67.cpp 2> file42d83c2e3b67.cpp.err.txt' had status 1
2: In file(con, "r") :
  cannot open file 'file42d83c2e3b67.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection"

I know that the 'schools.stan' file is there in the working directory and that I have access to it.

Here my ```sessionInfo()```, running through RStudio v. 1.3.959:
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
Matrix products: default
locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] rstan_2.19.3         ggplot2_3.3.1        StanHeaders_2.21.0-5
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       pillar_1.4.4       compiler_4.0.1     prettyunits_1.1.1 
 [5] tools_4.0.1        pkgbuild_1.0.8     lifecycle_0.2.0    tibble_3.0.1      
 [9] gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.6        cli_2.0.2         
[13] rstudioapi_0.11    parallel_4.0.1     xfun_0.14          loo_2.2.0         
[17] gridExtra_2.3      withr_2.2.0        dplyr_1.0.0        generics_0.0.2    
[21] vctrs_0.3.1        stats4_4.0.1       grid_4.0.1         tidyselect_1.1.0  
[25] glue_1.4.1         inline_0.3.15      R6_2.4.1           processx_3.4.2    
[29] fansi_0.4.1        purrr_0.3.4        callr_3.4.3        magrittr_1.5      
[33] matrixStats_0.56.0 scales_1.1.1       ps_1.3.3           ellipsis_0.3.1    
[37] assertthat_0.2.1   colorspace_1.4-1   tinytex_0.23       RcppParallel_5.0.1
[41] munsell_0.5.0      crayon_1.3.4

Any help appreciated!

**Comment by jgabry** [comment] 2020-06-24 14:31
Sorry you're getting an error. What happens if you specify the Stan program as a string instead of via a file (see below)? We don't generally recommend using a string, but trying it will tell us if the issue is really that it can't find the "schools.stan" file or if it's something else:  

```r
stan_code_string <- "
data {
  int<lower=0> J;         // number of schools 
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates 
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau;      // standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"

fit <- stan(model_code = stan_code_string, data = schools_dat)
```

**Comment by ivan-paleo** [comment] 2020-06-24 14:39
Thank you for the quick answer.
I get exactly the same error with the string.

**Comment by ivan-paleo** [comment] 2020-06-24 14:40
Note: I have installed R and all packages as admin, but I run RStudio as user without admin rights. But I just tried, and I get the same error when running RStudio as admin

**Comment by jgabry** [comment] 2020-06-24 15:08
Ah, I think I might know the problem. Can you try these two steps? 

1. Start a fresh R session without the rstan package loaded
2. Instead of library(rstan) use the `rstan::` qualifier to call `stan()`, so

```r
# don't do library(rstan)
fit <- rstan::stan('schools.stan', data = schools_dat)
```

If that works then I think the issue is a result of having `rstan_2.19.3` but `StanHeaders_2.21.0-5` installed (not your fault, it's just that the latest StanHeaders update made it through that CRAN process faster than the rstan update). That combination of mismatched versions is causing errors when rstan is loaded, but not loading it and using the `rstan::` qualifier is a workaround until rstan 2.21 makes it onto CRAN (that should be soon). Alternatively I think downgrading StanHeaders could also work, but not necessary if you're ok using `rstan::` in the short term. 

If that still doesn't work then I recommend posting to the Stan forums (http://discourse.mc-stan.org/) where you'll get more eyes on your question than in the GitHub issue tracker and hopefully someone will have the right solution.

**Comment by ivan-paleo** [comment] 2020-06-24 15:20
That did the trick!
I guess another possibility (and to me the easiest) would be to install the latest version of rstan from GitHub, like:
```install_github("stan-dev/rstan ")```

Would that work too?
If not, I'll stick to the ```rstan::```qualifier until the new version gets released.

Thank you!

**Comment by jgabry** [comment] 2020-06-24 15:56
Great, glad that worked! 

> I guess another possibility (and to me the easiest) would be to install the latest version of rstan from GitHub, like:
> `install_github("stan-dev/rstan ")`

I would think so, yeah, but if you do want to try it then you need a slightly different specification in `install_github()` because of the way the rstan repository is structured (it contains both rstan and StanHeaders). You would need something like: `install_github("stan-dev/rstan", subdir = "rstan/rstan")`. 

But it will be a lot slower than installing from CRAN since the version for windows on CRAN is a precompiled binary but on GitHub it would have to install from source and compile everything. I'm also not 100% sure that the issue that caused the delay with RStan 2.21 on CRAN is fully sorted out yet on GitHub (I'm not the one working on that), but it might be. Anyway, you could certainly give it a try though! Either way, at least you have the option of going back to using `rstan::` if necessary until the next release.

**Comment by jgabry** [comment] 2020-06-24 15:58
I closed this but actually I'm going to reopen and leave it open until rstan 2.21 makes it on to CRAN in case this is useful for anyone else.

**Comment by ivan-paleo** [comment] 2020-06-25 07:16
Installing from GitHub failed with this error:

compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.1/etc/x64/Makeconf:229: stanc.o] Error 1
ERROR: compilation failed for package 'rstan'
* removing 'C:/Program Files/R/R-4.0.1/library/rstan'
Error: Failed to install 'rstan' from GitHub:
  (converted from warning) installation of package ‘C:/Users/MONREP~1/AppData/Local/Temp/RtmpEP27nC/file479c792f5d49/rstan_2.6.0.tar.gz’ had non-zero exit status

So I'll stick to the ```rstan::``` until the 2.21 binaries are available on the CRAN.

**Comment by ivan-paleo** [comment] 2020-07-10 07:00
I have installed the new CRAN version (2.21.1).

Now I get a different error message (remember that I am using the example in the "Getting Started" guide):

> fit <- stan(file = 'schools.stan', data = schools_dat)
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In readLines(file, warn = TRUE) :
  incomplete final line found on 'C:\Users\calandra.RGZM\Documents\schools.stan'
2: In file.remove(c(unprocessed, processed)) :
  cannot remove file 'C:\Users\CALAND~1.RGZ\AppData\Local\Temp\RtmpMDZj2O\file5d02fe31f83.stan', reason 'No such file or directory'
3: In system(cmd, intern = !verbose) :
  running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file5d034ce4e3e.cpp 2> file5d034ce4e3e.cpp.err.txt' had status 1
4: In file(con, "r") :
  cannot open file 'file5d034ce4e3e.cpp.err.txt': No such file or directory
Error in sink(type = "output") : invalid connection

**Comment by ivan-paleo** [comment] 2020-07-10 07:02
Same problem if I write the model as a string as in your post above (https://github.com/stan-dev/rstan/issues/781#issuecomment-648857131).

And now, even that
`fit <- rstan::stan('schools.stan', data = schools_dat)`
does not work anymore...

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
Matrix products: default
locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] rstan_2.21.1         ggplot2_3.3.2        StanHeaders_2.21.0-5
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         compiler_4.0.2     pillar_1.4.5       prettyunits_1.1.1 
 [5] tools_4.0.2        pkgbuild_1.0.8     jsonlite_1.7.0     lifecycle_0.2.0   
 [9] tibble_3.0.2       gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.7       
[13] cli_2.0.2          rstudioapi_0.11    parallel_4.0.2     curl_4.3          
[17] xfun_0.15          loo_2.3.0          gridExtra_2.3      withr_2.2.0       
[21] dplyr_1.0.0        generics_0.0.2     vctrs_0.3.1        stats4_4.0.2      
[25] grid_4.0.2         tidyselect_1.1.0   glue_1.4.1         inline_0.3.15     
[29] R6_2.4.1           processx_3.4.3     fansi_0.4.1        callr_3.4.3       
[33] purrr_0.3.4        magrittr_1.5       codetools_0.2-16   matrixStats_0.56.0
[37] scales_1.1.1       ps_1.3.3           ellipsis_0.3.1     assertthat_0.2.1  
[41] colorspace_1.4-1   V8_3.2.0           tinytex_0.24       RcppParallel_5.0.2
[45] munsell_0.5.0      crayon_1.3.4

**Comment by stat-cz** [comment] 2020-07-14 10:13
> Same problem if I write the model as a string as in your post above ([#781 (comment)](https://github.com/stan-dev/rstan/issues/781#issuecomment-648857131)).
> 
> And now, even that
> `fit <- rstan::stan('schools.stan', data = schools_dat)`
> does not work anymore...
> 
> > sessionInfo()
> > R version 4.0.2 (2020-06-22)
> > Platform: x86_64-w64-mingw32/x64 (64-bit)
> > Running under: Windows 10 x64 (build 18362)
> > Matrix products: default
> > locale:
> > [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252
> > [3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C
> > [5] LC_TIME=English_United Kingdom.1252
> > attached base packages:
> > [1] stats     graphics  grDevices utils     datasets  methods   base
> > other attached packages:
> > [1] rstan_2.21.1         ggplot2_3.3.2        StanHeaders_2.21.0-5
> > loaded via a namespace (and not attached):
> > [1] Rcpp_1.0.5         compiler_4.0.2     pillar_1.4.5       prettyunits_1.1.1
> > [5] tools_4.0.2        pkgbuild_1.0.8     jsonlite_1.7.0     lifecycle_0.2.0
> > [9] tibble_3.0.2       gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.7
> > [13] cli_2.0.2          rstudioapi_0.11    parallel_4.0.2     curl_4.3
> > [17] xfun_0.15          loo_2.3.0          gridExtra_2.3      withr_2.2.0
> > [21] dplyr_1.0.0        generics_0.0.2     vctrs_0.3.1        stats4_4.0.2
> > [25] grid_4.0.2         tidyselect_1.1.0   glue_1.4.1         inline_0.3.15
> > [29] R6_2.4.1           processx_3.4.3     fansi_0.4.1        callr_3.4.3
> > [33] purrr_0.3.4        magrittr_1.5       codetools_0.2-16   matrixStats_0.56.0
> > [37] scales_1.1.1       ps_1.3.3           ellipsis_0.3.1     assertthat_0.2.1
> > [41] colorspace_1.4-1   V8_3.2.0           tinytex_0.24       RcppParallel_5.0.2
> > [45] munsell_0.5.0      crayon_1.3.4

did you solve this problem?

**Comment by stat-cz** [comment] 2020-07-14 10:14
did you solve this problem?


> I have installed the new CRAN version (2.21.1).
> 
> Now I get a different error message (remember that I am using the example in the "Getting Started" guide):
> 
> > fit <- stan(file = 'schools.stan', data = schools_dat)
> > The NEXT version of Stan will not be able to pre-process your Stan program.
> > Please open an issue at
> > https://github.com/stan-dev/stanc3/issues
> > if you can share or at least describe your Stan program. This will help ensure that Stan
> > continues to work on your Stan programs in the future. Thank you!
> > This message can be avoided by wrapping your function call inside suppressMessages().
> > Error in file(con, "r") : cannot open the connection
> > In addition: Warning messages:
> > 1: In readLines(file, warn = TRUE) :
> > incomplete final line found on 'C:\Users\calandra.RGZM\Documents\schools.stan'
> > 2: In file.remove(c(unprocessed, processed)) :
> > cannot remove file 'C:\Users\CALAND~1.RGZ\AppData\Local\Temp\RtmpMDZj2O\file5d02fe31f83.stan', reason 'No such file or directory'
> > 3: In system(cmd, intern = !verbose) :
> > running command 'C:/PROGRA~1/R/R-40~1.2/bin/x64/R CMD SHLIB file5d034ce4e3e.cpp 2> file5d034ce4e3e.cpp.err.txt' had status 1
> > 4: In file(con, "r") :
> > cannot open file 'file5d034ce4e3e.cpp.err.txt': No such file or directory
> > Error in sink(type = "output") : invalid connection

**Comment by ivan-paleo** [comment] 2020-07-14 10:26
No, I'm waiting for feedback to know how to solve it. But I've understood that rstan 2.21 seems to have big issues on Windows.

**Comment by ivan-paleo** [comment] 2020-07-14 10:29
And because of that, apparently brms is broken too...
https://www.mail-archive.com/r-help@r-project.org/msg258951.html

In other words, rstan 2.19 did not work well, and 2.21 does not work at all...

**Comment by ivan-paleo** [comment] 2020-07-16 12:32
See also these threads:
https://discourse.mc-stan.org/t/potential-problems-with-rstan-and-or-brms-packages-in-r-4-0-2/16479
 
https://discourse.mc-stan.org/t/error-in-compilecode-f-code-language-language-verbose-verbose-compilation-error-function-s-method-s-not-created-again/16466

**Comment by jgabry** [comment] 2020-07-20 16:46
And this thread: 

https://discourse.mc-stan.org/t/rstan-on-windows/16673

Does that help?

**Comment by ivan-paleo** [comment] 2020-08-03 12:54
Yes I have found it too.

**Closed as completed** 2020-09-04 20:08 UTC
