### ISSUE TITLE
Stan doesn't respect starting values for multiple chains

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstan#257] opened 2016-01-22 00:39 UTC
This was reported originally [over on the Stan issue tracker](https://github.com/stan-dev/stan/issues/1757#issuecomment-173761118) by @RobertMyles. I'm copying and pasting here as this is an RStan issue.

Here's the original message from @RobertMyles:

> Hi stan folks,
> First of all, thanks for stan, it's fantastic, and has saved me lots of time, as I was trying to run some ideal-point IRT models with JAGS and it was really slow. However, I'm having some trouble making stan use the initial values that I specify for my model (and initial values are important for these models). The model runs fine, it's a simple model, but never uses the initial values I provide. 
> 
> I have tried all the ways suggested in the R help for stan, and two ways are reproduced below in the toy example I provide. With one chain, there is no problem.  
> 
> Here's my example and thanks for any help:
> (I know it's a short run so error messages pop up about the treesize etc., but it's the initial values problem that I'm interested in)
> 
> ``` library(rstan)
> J <- 35
> K <- 50
> ThetaInit <- rnorm(J, 0, 1)
> ThetaInit[1] <- 1.5
> ThetaInit[2] <- -1.5
> BetaInit <- rnorm(K, 0, 3)
> AlphaInit <- rnorm(K, 0, 3)
> y <- matrix(rbinom(J*K, size=1, prob=0.5), J, K)
> 
> #My real data has plenty of NA, so just to keep the example similar to the real thing:
> 
> y[20, 12] <- NA
> y[5, 11] <- NA
> y[6, 2] <- NA
> 
> N <- length(y)
> j <- rep(1:J, times=K)
> k <- rep(1:K, each=J)
> 
> #delete missing values
> 
> missing <- which(is.na(y))
> N <- N - length(missing)
> j <- j[-missing]
> k <- k[-missing]
> y <- y[-missing]
> 
> #Model
> 
> stan.code <- "
> data {
>   int<lower=1> J;
>   int<lower=1> K;
>   int<lower=1> N;
>   int<lower=1, upper=J> j[N];
>   int<lower=1, upper=K> k[N];
>   int<lower=0, upper=1> y[N];
> }
> parameters {
>   real alpha[K];
>   real beta[K];
>   real theta[J];
> }
> model {
>   alpha ~ normal(0,3); 
>   beta ~ normal(0,3); 
>   theta ~ normal(0,1); 
>   theta[1] ~  normal(1, .001);
>   theta[2] ~ normal(-1, .001); 
> for (n in 1:N)
>   y[n] ~ bernoulli(Phi(theta[j[n]] * beta[k[n]] - alpha[k[n]]));
> }"
> 
> # Inits
>  # function form 2 with an argument named "chain_id"
>  # This is copied from ?stan
> 
> initf2 <- function(chain_id = 1) {
>   # cat("chain_id =", chain_id, "\n")
>   list(beta=list(BetaInit), theta=list(ThetaInit), alpha=list(AlphaInit))
> } 
> 
> # generate a list of lists to specify initial values
>  # Copied from ?stan
> 
> n_chains <- 4
> init_ll <- lapply(1:n_chains, function(id) initf2(chain_id = id))
> 
> stan.data <- list(J=J, K=K, N=N, j=j, k=k, y=y)
> 
> stan.fit <- stan(model_code=stan.code, data=stan.data,
>  iter=100, warmup=25, chains=4, thin=1,
>  init=init_ll, verbose=TRUE, cores=4, seed=1234)
> 
> get_inits(stan.fit)
> InitList <- get_inits(stan.fit)
> Theta1 <- InitList[[1]][3]
> Theta2 <- InitList[[2]][3]
> Theta3 <- InitList[[3]][3]
> Theta4 <- InitList[[4]][3]
> 
> Theta1[[1]][1] # all should be exactly 1.5
> [1] -0.8131447
> Theta2[[1]][1]
> [1] 1.644208
> Theta3[[1]][1]
> [1] 1.42286
> Theta4[[1]][1]
> [1] 0.3714791
> ```

**Comment by RobertMyles** [comment] 2016-01-29 16:17
Any chance that somebody could have a look into this issue if they have time? Thanks!

**Comment by jgabry** [comment] 2016-01-30 00:38
Thanks for the reminder. Personally I'm not very familiar with our code in RStan that deals with passing initial values to the sampler, so whichever dev did the inits coding should probably give this a look (I'm not sure if it's @maverickg or @bgoodri).

**Comment by maverickg** [comment] 2016-01-30 03:12
I tried the model here, 

```
data {
      int<lower=0> N;
      real y[N];
    }
    parameters {
      real mu;
      real alpha;
      simplex[3] delta;
      real eta;
      real<lower=0> sigma;
    }
    transformed parameters {
      real beta;
      beta <- -alpha;
    }
    model {
      mu ~ normal(0, 10);
      y ~ normal(mu, 1);
      alpha ~ normal(0, 1);
      eta ~ normal(0, 1);
      sigma ~ exponential(2);
    }
    generated quantities {
      real gamma;
      gamma <- mu + alpha;
    }
```

```
> fit <- stan(fit=fit, init=list(list(mu=2, alpha=-1, delta=rep(1,3)/3, eta=0.1, sigma=0.1), list(mu=3), list(mu=4)), data = dat,  cores=3,chains=3)
starting worker pid=17822 on localhost:11327 at 22:08:45.945
starting worker pid=17830 on localhost:11327 at 22:08:46.142
starting worker pid=17838 on localhost:11327 at 22:08:46.336

SAMPLING FOR MODEL '8e2b7fef3e7b143654c646561c54f8a3' NOW (CHAIN 1).

Chain 1, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1, Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 1, Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 1, Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 1, Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 1, Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 1, Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 1, Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 1, Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 1, Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 1, Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 1, Iteration: 2000 / 2000 [100%]  (Sampling)#
#  Elapsed Time: 0.029563 seconds (Warm-up)
#                0.027876 seconds (Sampling)
#                0.057439 seconds (Total)
#

SAMPLING FOR MODEL '8e2b7fef3e7b143654c646561c54f8a3' NOW (CHAIN 2).

Chain 2, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 2, Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 2, Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2, Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2, Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 2, Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 2, Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 2, Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 2, Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 2, Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 2, Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 2, Iteration: 2000 / 2000 [100%]  (Sampling)#
#  Elapsed Time: 0.033625 seconds (Warm-up)
#                0.026564 seconds (Sampling)
#                0.060189 seconds (Total)
#

SAMPLING FOR MODEL '8e2b7fef3e7b143654c646561c54f8a3' NOW (CHAIN 3).

Chain 3, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3, Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3, Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 3, Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 3, Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3, Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 3, Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3, Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 3, Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 3, Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 3, Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 3, Iteration: 2000 / 2000 [100%]  (Sampling)#
#  Elapsed Time: 0.035448 seconds (Warm-up)
#                0.027519 seconds (Sampling)
#                0.062967 seconds (Total)
#

> get_inits(fit)
[[1]]
[[1]]$mu
[1] 2

[[1]]$alpha
[1] -1

[[1]]$delta
[1] 0.3333333 0.3333333 0.3333333

[[1]]$eta
[1] 0.1

[[1]]$sigma
[1] 0.1

[[1]]$beta
[1] 1

[[1]]$gamma
[1] 1


[[2]]
[[2]]$mu
[1] 3

[[2]]$alpha
[1] 1.114803

[[2]]$delta
[1] 0.4815264 0.1861017 0.3323719

[[2]]$eta
[1] -1.671417

[[2]]$sigma
[1] 2.485884

[[2]]$beta
[1] -1.114803

[[2]]$gamma
[1] 4.114803


[[3]]
[[3]]$mu
[1] 4

[[3]]$alpha
[1] -0.05550619

[[3]]$delta
[1] 0.49304817 0.09788118 0.40907065

[[3]]$eta
[1] -0.7099755

[[3]]$sigma
[1] 0.6801948

[[3]]$beta
[1] 0.05550619

[[3]]$gamma
[1] 3.944494
```

It seems to be working well with specifying initials

**Comment by maverickg** [comment] 2016-01-30 03:18
I also tried the case init was specified using functions and that works well as the following indicates:

```
> initf <- function() list(mu=2, alpha=-1, delta=rep(1,3)/3, eta=0.1, sigma=0.2)
> fit <- stan(fit=fit, init=initf, data = dat,  cores=3,chains=3)
starting worker pid=17890 on localhost:11327 at 22:17:01.376
starting worker pid=17898 on localhost:11327 at 22:17:01.578
starting worker pid=17906 on localhost:11327 at 22:17:01.785

SAMPLING FOR MODEL '8e2b7fef3e7b143654c646561c54f8a3' NOW (CHAIN 1).

Chain 1, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1, Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 1, Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 1, Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 1, Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 1, Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 1, Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 1, Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 1, Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 1, Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 1, Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 1, Iteration: 2000 / 2000 [100%]  (Sampling)#
#  Elapsed Time: 0.031466 seconds (Warm-up)
#                0.027171 seconds (Sampling)
#                0.058637 seconds (Total)
#

SAMPLING FOR MODEL '8e2b7fef3e7b143654c646561c54f8a3' NOW (CHAIN 2).

Chain 2, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 2, Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 2, Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2, Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2, Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 2, Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 2, Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 2, Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 2, Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 2, Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 2, Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 2, Iteration: 2000 / 2000 [100%]  (Sampling)#
#  Elapsed Time: 0.028626 seconds (Warm-up)
#                0.028543 seconds (Sampling)
#                0.057169 seconds (Total)
#

SAMPLING FOR MODEL '8e2b7fef3e7b143654c646561c54f8a3' NOW (CHAIN 3).

Chain 3, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3, Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3, Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 3, Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 3, Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3, Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 3, Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3, Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 3, Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 3, Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 3, Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 3, Iteration: 2000 / 2000 [100%]  (Sampling)#
#  Elapsed Time: 0.031452 seconds (Warm-up)
#                0.026713 seconds (Sampling)
#                0.058165 seconds (Total)
#
> Warning message:
package ‘ggplot2’ was built under R version 3.2.3
Warning message:
package ‘ggplot2’ was built under R version 3.2.3
Warning message:
package ‘ggplot2’ was built under R version 3.2.3

> get_inits(fit)
[[1]]
[[1]]$mu
[1] 2

[[1]]$alpha
[1] -1

[[1]]$delta
[1] 0.3333333 0.3333333 0.3333333

[[1]]$eta
[1] 0.1

[[1]]$sigma
[1] 0.2

[[1]]$beta
[1] 1

[[1]]$gamma
[1] 1


[[2]]
[[2]]$mu
[1] 2

[[2]]$alpha
[1] -1

[[2]]$delta
[1] 0.3333333 0.3333333 0.3333333

[[2]]$eta
[1] 0.1

[[2]]$sigma
[1] 0.2

[[2]]$beta
[1] 1

[[2]]$gamma
[1] 1


[[3]]
[[3]]$mu
[1] 2

[[3]]$alpha
[1] -1

[[3]]$delta
[1] 0.3333333 0.3333333 0.3333333

[[3]]$eta
[1] 0.1

[[3]]$sigma
[1] 0.2

[[3]]$beta
[1] 1

[[3]]$gamma
[1] 1

```

**Comment by RobertMyles** [comment] 2016-01-31 13:17
@maverickg 
Thanks for the help, maverickg. But when I first used your two examples in my model, I got errors.
If I use a scalar for theta in my example model, as in your first example:

```
stan.fit <- stan(model_code=stan.code, data=stan.data,
                 iter=100, warmup=25, chains=3, thin=1,
                 init=list(list(theta=1, alpha=2, beta=3), list(theta=.5), list(theta=1.5)), 
                 verbose=TRUE, cores=3, seed=1234)
```

Then I get:

```
[1] "Error : Initialization partially from source failed."                                                                                                
[2] "mismatch in number dimensions declared and found in context; processing stage=initialization; variable name=theta; dims declared=(35); dims found=()"
```

Using rep() or indexes worked though. Thanks for the help, I'm not quite sure why it was going wrong earlier. Perhaps the examples on the rstan stan() help page could be clearer? When I use the method specified in ?stan, the function still doesn't use the inits. It is working fine with your examples though:

```
initF <- function() list(theta=c(1, -1, rnorm(J-2,0, 1)), alpha=rep(2, times=K), beta=rep(3, times=K))


> InitList <- get_inits(stan.fit)
> Theta1 <- InitList[[1]][3]
> Theta2 <- InitList[[2]][3]
> Theta3 <- InitList[[3]][3]
> Theta1[[1]][1]
[1] 1
> Theta1[[1]][2]
[1] -1
> Theta1[[1]][3]
[1] 2.229154
> Theta2[[1]][1]
[1] 1
> Theta2[[1]][2]
[1] -1
> Theta3[[1]][1]
[1] 1
> Theta3[[1]][2]
[1] -1
```

**Comment by RobertMyles** [comment] 2016-01-31 13:31
I also noticed that when the inits are specified outside the inits list itself, like:

```
ThetaInits <- rnorm(50, 0, 1)

initF <- function() list(theta=ThetaInits, alpha=rep(2, times=K), beta=rep(3, times=K))

```

Then rstan doesn't use this list and reports an error: `Error in init() : object 'ThetaInits' not found`

**Comment by bob-carpenter** [comment] 2016-01-31 22:18
I don't think there's a bug in RStan, so I'm going to close this issue.  I tried the above, and like the case Jiqiang tried, it works just as documented.

@RobertMyles : We'll need a script that we can run from a clean R session that reproduces what you think is a bug.  But the above works, as you'll see in the example here.

```
> prog <- "parameters { real theta; } model { theta ~ normal(0, 1); }"
> theta_inits <- rnorm(1, 10, 1)
> theta_inits
[1] 10.53447
> init_f <- function() { list(theta=theta_inits); }
> init_f()
$theta
[1] 10.53447

> library(rstan)
Loading required package: ggplot2
rstan (Version 2.9.0, packaged: 2016-01-05 16:17:47 UTC, GitRev: 05c3d0058b6a)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
> fit <- stan(model_code=prog, init=init_f)

SAMPLING FOR MODEL '2d139e79d9b61d1901c83cf78f1b1bf9' NOW (CHAIN 1).

Chain 1, Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1, Iteration:  200 / 2000 [ 10%]  (Warmup)
...
```

**Closed as completed by bob-carpenter** 2016-01-31 22:18 UTC

**Comment by jgabry** [comment] 2016-01-31 22:23
Thanks Bob and Mav.

**Comment by RobertMyles** [comment] 2016-02-01 19:37
Hi all, thanks again for taking the time to look into this issue, and I'm sorry if my previous post wasn't clear. In the example below, I have copied and pasted my original example, but this time I have three runs of stan, each one using the different methods for specifying inits on this thread.

stan.fit1 uses the method shown on the R help for rstan, and as you can see, it does not use the inits specified.

stan.fit2 uses maverickg's method, and the inits are used fine.

stan.fit3 uses Bob's method and the object 'ThetaInits' is not used by rstan, in fact rstan gives an error and won't run.

I have included my session Info. I really hope I'm not making any stupid mistakes here and wasting all your time, but it does seem to me to be a problem. 

```
library(rstan)
J <- 15
K <- 10
y <- matrix(rbinom(J*K, size=1, prob=0.5), J, K)
# My real data has plenty of NA, so just to keep the example similar to the real thing:
y[20, 12] <- NA
y[5, 11] <- NA
y[6, 2] <- NA

N <- length(y)
j <- rep(1:J, times=K)
k <- rep(1:K, each=J)

#delete missing values
missing <- which(is.na(y))
N <- N - length(missing)
j <- j[-missing]
k <- k[-missing]
y <- y[-missing]

###  Model
stan.code <- "
data {
  int<lower=1> J;
  int<lower=1> K;
  int<lower=1> N;
  int<lower=1, upper=J> j[N];
  int<lower=1, upper=K> k[N];
  int<lower=0, upper=1> y[N];
}
parameters {
  real alpha[K];
  real beta[K];
  real theta[J];
}
model {
  alpha ~ normal(0,3); 
  beta ~ normal(0,3); 
  theta ~ normal(0,1); 
  theta[1] ~  normal(1, .001);
  theta[2] ~ normal(-1, .001); 
for (n in 1:N)
  y[n] ~ bernoulli(Phi(theta[j[n]] * beta[k[n]] - alpha[k[n]]));
}"


### Inits
ThetaInit <- rnorm(J, 0, 1)
ThetaInit[1] <- 1
ThetaInit[2] <- -1
BetaInit <- rnorm(K, 0, 3)
AlphaInit <- rnorm(K, 0, 3)

# function form 2 with an argument named `chain_id`
# This is copied from ?stan
initf2 <- function(chain_id = 1) {
  # cat("chain_id =", chain_id, "\n")
  list(beta=list(BetaInit), theta=list(ThetaInit), alpha=list(AlphaInit))
} 
# # generate a list of lists to specify initial values
# Copied from ?stan
n_chains <- 4
init_ll <- lapply(1:n_chains, function(id) initf2(chain_id = id))

### maverickg's method:
initF <- function() list(theta=c(1, -1, rnorm(J-2,0, 1)), alpha=rep(2, times=K), beta=rep(3, times=K))

## Bob's method:
init_f <- function() { list(theta=ThetaInit); }

stan.data <- list(J=J, K=K, N=N, j=j, k=k, y=y)

stan.fit1 <- stan(model_code=stan.code, data=stan.data, iter=100, warmup=25, chains=4, thin=1, init=init_ll, verbose=TRUE, cores=4, seed=1234)

get_inits(stan.fit1)

[[1]]
[[1]]$alpha
 [1]  1.99844161  0.22862099  1.98023596 -1.88983224  0.35815467  0.20948985 -1.31221456
 [8] -0.05479312  1.61701713 -0.17321668

[[1]]$beta
 [1] -1.13044593  1.83614949 -1.83698387  1.43098962  1.96814275  0.24854793  0.33234265
 [8]  0.59360366 -0.82247026 -0.04250235

[[1]]$theta
 [1] -0.98656468 -1.68209812 -0.34015936  1.03429591  0.63743338  1.40683404  0.76578999
 [8]  1.98518879 -0.91368343  0.36051820  0.78061938  0.55633211  0.93350588 -0.44694254
[15] -0.05296021


[[2]]
[[2]]$alpha
 [1] -0.7987087  1.3026517  0.4207658  0.2789249 -1.9266277  1.1899950 -1.7845694 -1.3020129
 [9] -0.3716931  0.1575278

[[2]]$beta
 [1]  1.3235084  1.6955042 -1.7768832 -0.5582212  0.2786070 -0.9884534 -1.9937118 -1.0510877
 [9]  1.1156265  0.0221116

[[2]]$theta
 [1] -0.930520998 -0.145623597  0.837880295 -0.825599094  0.053062860  0.625878223 -1.774763560
 [8]  1.206623198  1.211395629  1.508034392  0.009086771  0.142228752  1.061246957  1.696393358
[15] -1.549357866


[[3]]
[[3]]$alpha
 [1] -1.3795172  1.7152282 -0.5481697  1.4677633  1.3188718  0.7252130  1.9983619 -1.2010258
 [9]  1.2256399 -1.9801758

[[3]]$beta
 [1]  0.4335470  0.3936416  1.9950010 -1.6385773  1.0969388 -0.4019132  0.5198583 -1.9714876
 [9]  1.0312466 -1.7407859

[[3]]$theta
 [1]  0.31362811 -0.79900810  0.50023712 -0.12750170  0.97339726  0.70888745  0.19881688
 [8]  0.22806041  1.68777847 -0.01568977 -1.84127300 -0.21061261  0.57161468 -0.60020290
[15]  1.75303342


[[4]]
[[4]]$alpha
 [1] -1.32814076 -1.01538562 -1.41777193 -1.65149425 -1.28337748 -0.13751170 -0.08944603
 [8] -1.10370640 -0.69211481  1.71797914

[[4]]$beta
 [1] -0.8789091 -0.4575151  0.1003531 -1.3263561 -1.8720334  0.1068839  0.2234589 -1.9103632
 [9] -1.9144892 -0.7642573

[[4]]$theta
 [1]  0.3009330  1.8356924  1.2895814 -1.5503450 -0.5173956 -1.9114713  0.4186017  0.6948498
 [9] -0.6307776  1.4403399 -1.9260814 -1.3323717 -1.6539699  0.3974409  0.7466204


stan.fit2 <- stan(model_code=stan.code, data=stan.data, iter=100, warmup=25, chains=4, thin=1, init=initF, verbose=TRUE, cores=4, seed=1234)

get_inits(stan.fit2)

[[1]]
[[1]]$alpha
 [1] 2 2 2 2 2 2 2 2 2 2

[[1]]$beta
 [1] 3 3 3 3 3 3 3 3 3 3

[[1]]$theta
 [1]  1.00000000 -1.00000000  0.56699414  0.75427039  2.23507165 -1.38955840  1.81306794
 [8]  1.49501978 -0.80370867  0.62819602  2.25297478 -0.26078423  0.06875528 -0.74249671
[15]  1.94043587


[[2]]
[[2]]$alpha
 [1] 2 2 2 2 2 2 2 2 2 2

[[2]]$beta
 [1] 3 3 3 3 3 3 3 3 3 3

[[2]]$theta
 [1]  1.00000000 -1.00000000  0.88222154 -0.40950617  0.07567991  1.95150329  0.92830104
 [8] -0.78396414 -0.72284473 -0.57437523  1.52806750  0.49358327  0.43718353 -0.78426090
[15] -0.96131578


[[3]]
[[3]]$alpha
 [1] 2 2 2 2 2 2 2 2 2 2

[[3]]$beta
 [1] 3 3 3 3 3 3 3 3 3 3

[[3]]$theta
 [1]  1.0000000 -1.0000000 -1.0051678  0.3283070 -0.8301398 -0.1882966 -0.1007797 -3.3194645
 [9] -0.9986525 -0.2333237  1.0948175  0.4039208 -1.0342667  0.3323569  1.1184733


[[4]]
[[4]]$alpha
 [1] 2 2 2 2 2 2 2 2 2 2

[[4]]$beta
 [1] 3 3 3 3 3 3 3 3 3 3

[[4]]$theta
 [1]  1.00000000 -1.00000000 -1.02014551  0.35585502  0.39893868  0.27982685  0.30117735
 [8] -0.24227404 -1.85280663 -1.30294343  0.87305894 -0.02967713 -0.04778955  0.45147921
[15]  0.58746637


stan.fit3 <- stan(model_code=stan.code, data=stan.data, iter=100, warmup=25, chains=4, thin=1, init=init_f, verbose=TRUE, cores=4, seed=1234)

...

Error in init() : object 'ThetaInit' not found
error in specifying arguments; sampling not done
```

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.9.0   ggplot2_2.0.0

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 scales_0.3.0     plyr_1.8.3       parallel_3.2.3   tools_3.2.3     
 [6] inline_0.3.14    gtable_0.1.2     gridExtra_2.0.0  Rcpp_0.12.3      codetools_0.2-14
[11] grid_3.2.3       stats4_3.2.3     munsell_0.4.2   
```

**Comment by bgoodri** [comment] 2016-02-01 19:51
I think this

```
Error in init() : object 'ThetaInit' not found

error in specifying arguments; sampling not done
```

occurs because ThetaInit is an object in the GlobalEnv of the parent R
process and cannot be accessed via the usual scoping mechanisms by any of
the child R processes. In other words, the init function is exported to the
child R processes so that it can be called but it can only refer to
chain_id because everything else in the parent process is out of scope.

**Comment by RobertMyles** [comment] 2016-02-03 10:54
The problem is that external inits, outside the scope of any init list or function, need to be fed to rstan as part of the `data` in the call to stan(). I didn't see this mentioned in the rstan help for stan() and so I didn't realise that it was necessary. Perhaps you could update the rstan help to include this? It would help a lot for people like me who are migrating from JAGS and who use the examples and the help as a way to learn stan.

Thanks to all who helped with this problem.

Robert

**Comment by bob-carpenter** [comment] 2016-02-03 18:10
I agree, so I created the doc issue:

https://github.com/stan-dev/rstan/issues/260
- Bob
