### ISSUE TITLE
Speed up rstan using dso objects?

### ISSUE THREAD

**Issue by wiligl** [stan-dev/rstan#202] opened 2015-09-08 13:36 UTC
Hi,

I am using rstan to perform simple Bayesian hierarchical models in various (small) summary data sets.
rstan performs really slow in terms of time required for compilation and computation. I wonder, what the best way is to speed up rstan, e.g. compiling the model in CPP to a dynamic shared object and feeding it with varying datasets to skip the compilation step? Any recommendations and examples welcome!

Best, Will

**Comment by syclik** [comment] 2015-09-08 13:49
1. There are already ways of saving compiled Stan programs. In RStan, I believe you can serial and deserialize from disk. I believe @bgoodri and @jgabry are working on a package that will have models already compiled for most architectures so you won't even need a compiler to run a handful of fixed models.
2. Regarding speeding up compiling the C++: we've been searching for a solution, but this is an open problem. We've tried precompiled headers and shared objects to no avail. The problem is that the C++ is written as templated C++ with everything specific about a Stan program being compiled after the C++ is generated. In short, we have no immediate solution, but we go to the web to see if anyone's made progress a few times a year.
3. You can already feed in multiple data sets to the same model. From the R session, type `?stan` and you should see an example for feeding in a `stanfit` object. It works sort of like this: `fit <- stan('stan_program.stan', data=data1); fit2 <- stan(fit=fit, data=data2);` For that second call, you avoid compiling the program.

If this is enough info for now, can you close the issue since it's not really an issue unless you have something else? (If you don't have permissions to close your own issue, then just comment that it's ok to close and I'll close it.)

**Comment by wiligl** [comment] 2015-09-08 13:53
Thank you very much! Best, Will

**Closed as completed** 2015-09-08 13:52 UTC
