### ISSUE TITLE
extract(..., pars=...) fails when the library `tidyr` is loaded

### ISSUE THREAD

**Issue by tpapp** [stan-dev/rstan#185] opened 2015-08-07 13:49 UTC
Example code (from the help page of `extract`, + loading libs):

``` R
library(rstan)
library(tidyr)
ex_model_code <- '
       parameters {
         real alpha[2,3];
         real beta[2]; 
       } 
       model {
         for (i in 1:2) for (j in 1:3) 
           alpha[i, j] ~ normal(0, 1); 
         for (i in 1:2) 
           beta ~ normal(0, 2); 
       } 
     '
fit <- stan(model_code = ex_model_code, chains = 4) 
alpha2 <- extract(fit, pars = 'alpha', permuted = TRUE)$alpha 
```

Backtrace:

``` R
> alpha2 <- extract(fit, pars = 'alpha', permuted = TRUE)$alpha 
Error: Please supply column name

Enter a frame number, or 0 to exit   

1: extract(fit, pars = "alpha", permuted = TRUE)
2: col_name(substitute(col))
```

Version info:

``` R
> packageVersion("rstan")
[1] ‘2.7.0.2’
> packageVersion("tidyr")
[1] ‘0.2.0’
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.2.0   rstan_2.7.0-2 Rcpp_0.12.0  

loaded via a namespace (and not attached):
[1] compiler_3.2.1   tools_3.2.1      inline_0.3.14    codetools_0.2-14
[5] stats4_3.2.1    
```

**Comment by jrnold** [comment] 2015-08-07 15:49
The issue is that both **rstan** and **tidyr** include `extract` functions, so whatever package is loaded last masks the function from the earlier package.  See issue #118. When you load `tidyr` after rstan you should see the message.

``` Rconsole
> library(tidyr)

Attaching package: ‘tidyr’

The following object is masked from ‘package:rstan’:

    extract
```

This is common in R. For example, **dplyr** masks several **base** R functions, like `filter`.

The solution is to use `::` to explicitly specify the package from which you are getting the function.

``` R
alpha2 <- rstan::extract(fit, pars = 'alpha', permuted = TRUE)$alpha 
```

**Comment by jgabry** [comment] 2015-08-07 15:55
Or you can use one of the as.\* functions (as.matrix, as.array, etc.)
instead of explicitly calling extract. That should work if you don't need
the warmup draws.

**Comment by bgoodri** [comment] 2015-08-07 17:31
Closing as a duplicate of #118 but what Jeff and Jonah said is good advice.

**Closed as completed by bgoodri** 2015-08-07 17:31 UTC
