### ISSUE TITLE
rstan::stanc_builder() causes memory usage to increase rapidly

### ISSUE THREAD

**Issue by cm421** [stan-dev/rstan#945] opened 2021-06-14 21:01 UTC
#### Summary:
Repeated calls to `rstan::stanc_builder()` causes `R`'s memory usage to increase rapidly

#### Description:
Every time I call `rstan::stanc_builder()` `R`'s memory usage increases by 5-40MB each time. A handful of calls is enough to easily eat through 0.5-1GB. 

`gc()` doesn't clear out the used up memory either. If `rstan` is doing some sort of caching of previous builds/models or otherwise holding something in memory intentionally, I would expect an explicit call to `gc()` to cause `rstan` to clear those out. 

I see the same behavior on both MacOS and Windows 10.

#### Reproducible Steps:
I originally came across this behavior editing a `.stan` file in RStudio. RStudio exacerbates this issue because it calls `rstan::stanc_builder()` every time the file is saved, and by default RStudio will autosave a `.stan` after every 1-2 second pause from typing. A few minutes of typing/pausing to think can eat through a lot of memory very quickly.

Using [RStudio's template .stan file](https://github.com/rstudio/rstudio/blob/df86b69ebdf62f1a9ed51af59c168572677541f1/src/cpp/session/resources/templates/stan.stan) I'm able to reproduce the same behavior I saw in RStudio in the terminal by:

1. Save that template file somewhere
2. Launch `R` in the terminal
3. Open up Activity Monitor and find the `R` process under the Memory tab
4. Load `rstan` and call `stanc_builder` on the saved file
  > \> library(rstan)
  Loading required package: StanHeaders
  Loading required package: ggplot2
  rstan (Version 2.21.2, GitRev: 2e1f913d3ca3)
  For execution on a local, multicore CPU with excess RAM we recommend calling
  options(mc.cores = parallel::detectCores()).
  To avoid recompilation of unchanged Stan programs, we recommend calling
  rstan_options(auto_write = TRUE)
  \> rstan::stanc_builder("test.stan")
5. `R`'s memory usage increases anywhere from 5-40MB. Several back-to-back calls increases the memory usage rapidly.

#### Current Output:
Not sure if it's useful, but the output from the `rstan::stanc_builder()` command on that template file on my Mac:
<details>
  <summary>Click to expand</summary>
> rstan::stanc_builder("test.stan")
$status
[1] TRUE

$model_cppname
[1] "model_test"

$cppcode
[1] "// Code generated by Stan version 2.21.0\n\n#include <stan/model/model_header.hpp>\n\nnamespace model_test_namespace {\n\nusing std::istream;\nusing std::string;\nusing std::stringstream;\nusing std::vector;\nusing stan::io::dump;\nusing stan::math::lgamma;\nusing stan::model::prob_grad;\nusing namespace stan::math;\n\nstatic int current_statement_begin__;\n\nstan::io::program_reader prog_reader__() {\n    stan::io::program_reader reader;\n    reader.add_event(0, 0, \"start\", \"model_test\");\n    reader.add_event(15, 13, \"end\", \"model_test\");\n    return reader;\n}\n\nclass model_test\n  : public stan::model::model_base_crtp<model_test> {\nprivate:\n        int N;\n        vector_d y;\npublic:\n    model_test(stan::io::var_context& context__,\n        std::ostream* pstream__ = 0)\n        : model_base_crtp(0) {\n        ctor_body(context__, 0, pstream__);\n    }\n\n    model_test(stan::io::var_context& context__,\n        unsigned int random_seed__,\n        std::ostream* pstream__ = 0)\n        : model_base_crtp(0) {\n        ctor_body(context__, random_seed__, pstream__);\n    }\n\n    void ctor_body(stan::io::var_context& context__,\n                   unsigned int random_seed__,\n                   std::ostream* pstream__) {\n        typedef double local_scalar_t__;\n\n        boost::ecuyer1988 base_rng__ =\n          stan::services::util::create_rng(random_seed__, 0);\n        (void) base_rng__;  // suppress unused var warning\n\n        current_statement_begin__ = -1;\n\n        static const char* function__ = \"model_test_namespace::model_test\";\n        (void) function__;  // dummy to suppress unused var warning\n        size_t pos__;\n        (void) pos__;  // dummy to suppress unused var warning\n        std::vector<int> vals_i__;\n        std::vector<double> vals_r__;\n        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());\n        (void) DUMMY_VAR__;  // suppress unused var warning\n\n        try {\n            // initialize data block variables from context__\n            current_statement_begin__ = 2;\n            context__.validate_dims(\"data initialization\", \"N\", \"int\", context__.to_vec());\n            N = int(0);\n            vals_i__ = context__.vals_i(\"N\");\n            pos__ = 0;\n            N = vals_i__[pos__++];\n            check_greater_or_equal(function__, \"N\", N, 0);\n\n            current_statement_begin__ = 3;\n            validate_non_negative_index(\"y\", \"N\", N);\n            context__.validate_dims(\"data initialization\", \"y\", \"vector_d\", context__.to_vec(N));\n            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);\n            vals_r__ = context__.vals_r(\"y\");\n            pos__ = 0;\n            size_t y_j_1_max__ = N;\n            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {\n                y(j_1__) = vals_r__[pos__++];\n            }\n\n\n            // initialize transformed data variables\n            // execute transformed data statements\n\n            // validate transformed data\n\n            // validate, set parameter ranges\n            num_params_r__ = 0U;\n            param_ranges_i__.clear();\n            current_statement_begin__ = 7;\n            num_params_r__ += 1;\n            current_statement_begin__ = 8;\n            num_params_r__ += 1;\n        } catch (const std::exception& e) {\n            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());\n            // Next line prevents compiler griping about no return\n            throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\");\n        }\n    }\n\n    ~model_test() { }\n\n\n    void transform_inits(const stan::io::var_context& context__,\n                         std::vector<int>& params_i__,\n                         std::vector<double>& params_r__,\n                         std::ostream* pstream__) const {\n        typedef double local_scalar_t__;\n        stan::io::writer<double> writer__(params_r__, params_i__);\n        size_t pos__;\n        (void) pos__; // dummy call to supress warning\n        std::vector<double> vals_r__;\n        std::vector<int> vals_i__;\n\n        current_statement_begin__ = 7;\n        if (!(context__.contains_r(\"mu\")))\n            stan::lang::rethrow_located(std::runtime_error(std::string(\"Variable mu missing\")), current_statement_begin__, prog_reader__());\n        vals_r__ = context__.vals_r(\"mu\");\n        pos__ = 0U;\n        context__.validate_dims(\"parameter initialization\", \"mu\", \"double\", context__.to_vec());\n        double mu(0);\n        mu = vals_r__[pos__++];\n        try {\n            writer__.scalar_unconstrain(mu);\n        } catch (const std::exception& e) {\n            stan::lang::rethrow_located(std::runtime_error(std::string(\"Error transforming variable mu: \") + e.what()), current_statement_begin__, prog_reader__());\n        }\n\n        current_statement_begin__ = 8;\n        if (!(context__.contains_r(\"sigma\")))\n            stan::lang::rethrow_located(std::runtime_error(std::string(\"Variable sigma missing\")), current_statement_begin__, prog_reader__());\n        vals_r__ = context__.vals_r(\"sigma\");\n        pos__ = 0U;\n        context__.validate_dims(\"parameter initialization\", \"sigma\", \"double\", context__.to_vec());\n        double sigma(0);\n        sigma = vals_r__[pos__++];\n        try {\n            writer__.scalar_lb_unconstrain(0, sigma);\n        } catch (const std::exception& e) {\n            stan::lang::rethrow_located(std::runtime_error(std::string(\"Error transforming variable sigma: \") + e.what()), current_statement_begin__, prog_reader__());\n        }\n\n        params_r__ = writer__.data_r();\n        params_i__ = writer__.data_i();\n    }\n\n    void transform_inits(const stan::io::var_context& context,\n                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,\n                         std::ostream* pstream__) const {\n      std::vector<double> params_r_vec;\n      std::vector<int> params_i_vec;\n      transform_inits(context, params_i_vec, params_r_vec, pstream__);\n      params_r.resize(params_r_vec.size());\n      for (int i = 0; i < params_r.size(); ++i)\n        params_r(i) = params_r_vec[i];\n    }\n\n\n    template <bool propto__, bool jacobian__, typename T__>\n    T__ log_prob(std::vector<T__>& params_r__,\n                 std::vector<int>& params_i__,\n                 std::ostream* pstream__ = 0) const {\n\n        typedef T__ local_scalar_t__;\n\n        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());\n        (void) DUMMY_VAR__;  // dummy to suppress unused var warning\n\n        T__ lp__(0.0);\n        stan::math::accumulator<T__> lp_accum__;\n        try {\n            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);\n\n            // model parameters\n            current_statement_begin__ = 7;\n            local_scalar_t__ mu;\n            (void) mu;  // dummy to suppress unused var warning\n            if (jacobian__)\n                mu = in__.scalar_constrain(lp__);\n            else\n                mu = in__.scalar_constrain();\n\n            current_statement_begin__ = 8;\n            local_scalar_t__ sigma;\n            (void) sigma;  // dummy to suppress unused var warning\n            if (jacobian__)\n                sigma = in__.scalar_lb_constrain(0, lp__);\n            else\n                sigma = in__.scalar_lb_constrain(0);\n\n            // model body\n\n            current_statement_begin__ = 12;\n            lp_accum__.add(normal_log<propto__>(y, mu, sigma));\n\n        } catch (const std::exception& e) {\n            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());\n            // Next line prevents compiler griping about no return\n            throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\");\n        }\n\n        lp_accum__.add(lp__);\n        return lp_accum__.sum();\n\n    } // log_prob()\n\n    template <bool propto, bool jacobian, typename T_>\n    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,\n               std::ostream* pstream = 0) const {\n      std::vector<T_> vec_params_r;\n      vec_params_r.reserve(params_r.size());\n      for (int i = 0; i < params_r.size(); ++i)\n        vec_params_r.push_back(params_r(i));\n      std::vector<int> vec_params_i;\n      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);\n    }\n\n\n    void get_param_names(std::vector<std::string>& names__) const {\n        names__.resize(0);\n        names__.push_back(\"mu\");\n        names__.push_back(\"sigma\");\n    }\n\n\n    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {\n        dimss__.resize(0);\n        std::vector<size_t> dims__;\n        dims__.resize(0);\n        dimss__.push_back(dims__);\n        dims__.resize(0);\n        dimss__.push_back(dims__);\n    }\n\n    template <typename RNG>\n    void write_array(RNG& base_rng__,\n                     std::vector<double>& params_r__,\n                     std::vector<int>& params_i__,\n                     std::vector<double>& vars__,\n                     bool include_tparams__ = true,\n                     bool include_gqs__ = true,\n                     std::ostream* pstream__ = 0) const {\n        typedef double local_scalar_t__;\n\n        vars__.resize(0);\n        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);\n        static const char* function__ = \"model_test_namespace::write_array\";\n        (void) function__;  // dummy to suppress unused var warning\n\n        // read-transform, write parameters\n        double mu = in__.scalar_constrain();\n        vars__.push_back(mu);\n\n        double sigma = in__.scalar_lb_constrain(0);\n        vars__.push_back(sigma);\n\n        double lp__ = 0.0;\n        (void) lp__;  // dummy to suppress unused var warning\n        stan::math::accumulator<double> lp_accum__;\n\n        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());\n        (void) DUMMY_VAR__;  // suppress unused var warning\n\n        if (!include_tparams__ && !include_gqs__) return;\n\n        try {\n            if (!include_gqs__ && !include_tparams__) return;\n            if (!include_gqs__) return;\n        } catch (const std::exception& e) {\n            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());\n            // Next line prevents compiler griping about no return\n            throw std::runtime_error(\"*** IF YOU SEE THIS, PLEASE REPORT A BUG ***\");\n        }\n    }\n\n    template <typename RNG>\n    void write_array(RNG& base_rng,\n                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,\n                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,\n                     bool include_tparams = true,\n                     bool include_gqs = true,\n                     std::ostream* pstream = 0) const {\n      std::vector<double> params_r_vec(params_r.size());\n      for (int i = 0; i < params_r.size(); ++i)\n        params_r_vec[i] = params_r(i);\n      std::vector<double> vars_vec;\n      std::vector<int> params_i_vec;\n      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);\n      vars.resize(vars_vec.size());\n      for (int i = 0; i < vars.size(); ++i)\n        vars(i) = vars_vec[i];\n    }\n\n    std::string model_name() const {\n        return \"model_test\";\n    }\n\n\n    void constrained_param_names(std::vector<std::string>& param_names__,\n                                 bool include_tparams__ = true,\n                                 bool include_gqs__ = true) const {\n        std::stringstream param_name_stream__;\n        param_name_stream__.str(std::string());\n        param_name_stream__ << \"mu\";\n        param_names__.push_back(param_name_stream__.str());\n        param_name_stream__.str(std::string());\n        param_name_stream__ << \"sigma\";\n        param_names__.push_back(param_name_stream__.str());\n\n        if (!include_gqs__ && !include_tparams__) return;\n\n        if (include_tparams__) {\n        }\n\n        if (!include_gqs__) return;\n    }\n\n\n    void unconstrained_param_names(std::vector<std::string>& param_names__,\n                                   bool include_tparams__ = true,\n                                   bool include_gqs__ = true) const {\n        std::stringstream param_name_stream__;\n        param_name_stream__.str(std::string());\n        param_name_stream__ << \"mu\";\n        param_names__.push_back(param_name_stream__.str());\n        param_name_stream__.str(std::string());\n        param_name_stream__ << \"sigma\";\n        param_names__.push_back(param_name_stream__.str());\n\n        if (!include_gqs__ && !include_tparams__) return;\n\n        if (include_tparams__) {\n        }\n\n        if (!include_gqs__) return;\n    }\n\n}; // model\n\n}  // namespace\n\ntypedef model_test_namespace::model_test stan_model;\n\n#ifndef USING_R\n\nstan::model::model_base& new_model(\n        stan::io::var_context& data_context,\n        unsigned int seed,\n        std::ostream* msg_stream) {\n  stan_model* m = new stan_model(data_context, seed, msg_stream);\n  return *m;\n}\n\n#endif\n\n"

$model_name
[1] "test"

$model_code
[1] "data {\n  int<lower=0> N;\n  vector[N] y;\n}\n\nparameters {\n  real mu;\n  real<lower=0> sigma;\n}\n\nmodel {\n  y ~ normal(mu, sigma);\n}\n"
attr(,"model_name2")
[1] "paste(program, collapse = \"\\n\")"

</details>

#### Expected Output:
No expected output, per se, but the expected behavior would be that a more reasonable amount of memory be used. If large amounts of memory are required then I would expect a call to `gc()` would clear out memory that I've decided I don't need anymore.

#### RStan Version:
Same version on MacOS and Windows 10:
rstan (Version 2.21.2, GitRev: 2e1f913d3ca3)

#### R Version:
On MacOS:
> \> R.version.string
[1] "R version 4.0.5 (2021-03-31)"

On Windows:
> \> R.version.string
[1] "R version 3.6.3 (2020-02-29)"
 
#### Operating System:
MacOS 11.4
Windows 10 Build 19042.631

**Comment by SteveBronder** [comment] 2021-06-15 04:03
I wonder if this is caused by v8 in `stanc_beta()`? Like maybe we need to load up one v8 and nightly build of stanc3 on package startup and use that? I can try this out tmrw

**Comment by SteveBronder** [comment] 2021-06-15 14:42
@cm421 would you mind trying to build this branch of rstan locally?

https://github.com/stan-dev/rstan/tree/fix-attempt/v8-mem

Taking a test file and doing 

```r
for (i in 1:500) {
  stanc_builder("../test_file.stan")
}
```

I didn't see a memory increase in the rsession or rstudio via `top`. If that works then I can open up a PR to fix this up

**Comment by cm421** [comment] 2021-06-15 18:29
Thanks for the responsive fix! Trying this out on MacOS I'm seeing _much_ better memory performance already.

I'm taking that with a slight grain of salt because I'm also seeing a few errors:

When I run a solitary `stanc_builder("test.stan")` command it seems to run, but at the end I get an error:

> Warning message:
In system(paste(CPP, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  error in running command

When I run in a loop all I see is:

> ...
> 'config' variable 'CPP' is deprecated
> clang -E
> 'config' variable 'CPP' is deprecated
> clang -E
> 'config' variable 'CPP' is deprecated
> clang -E
> There were 50 or more warnings (use warnings() to see the first 50)

I'm kicking myself for forgetting to include this in my initial post, but I noticed that when I call `stanc_builder` on a `.stan` file with a syntax error, I do **not** get any memory jumps/increases. So these warnings might be significant for that reason, or maybe my machine is set up wrong.

Trying out on a Windows machine and a clean Linux install right now as a sanity check and will report back.

**Comment by cm421** [comment] 2021-06-15 19:09
Seeing similar improvements (and same warnings) on Linux as well, but I feel more confident that it's working now!

Testing it out in both the terminal and RStudio appears to be working the same as well. Great work!

**Comment by SteveBronder** [comment] 2021-06-15 19:12
Huh! Okay let me try to figure out that CPP deprecated message, @hsbadr would it be better to make a branch off of the experimental branch to work on this?

> I'm kicking myself for forgetting to include this in my initial post, but I noticed that when I call stanc_builder on a .stan file with a syntax error, I do not get any memory jumps/increases. So these warnings might be significant for that reason, or maybe my machine is set up wrong.

idt your machine is setup wrong, that seems like a thing that would be odd to happen only on a certain setup.

**Comment by hsbadr** [comment] 2021-06-15 19:27
> @hsbadr would it be better to make a branch off of the experimental branch to work on this?

Sure. These warnings are fixed there (we now use `$CC -E` instead of the R-deprecated `$CPP` for the C preprocessor).

**Comment by hsbadr** [comment] 2021-06-15 19:31
That's now defunct:
```bash
> R CMD config CPP
'config' variable 'CPP' is defunct
```

```bash
> R CMD config CC
gcc
```

Anyway, it's fixed in the experimental branch.

**Comment by maxbiostat** [comment] 2021-06-15 19:55
How do I try these fixes, i.e.,  (i) how do I install from a branch and (ii) which branch should I install? Please, forgive my ignorance.

**Comment by hsbadr** [comment] 2021-06-15 20:00
> How do I try these fixes, i.e., (i) how do I install from a branch and (ii) which branch should I install? Please, forgive my ignorance.

No worries. The experimental branch will fix the warnings above. It doesn't include @SteveBronder's patch yet.

```r
  remotes::install_git("https://github.com/stan-dev/rstan", subdir = "StanHeaders", ref = "experimental")
  remotes::install_git("https://github.com/stan-dev/rstan", subdir = "rstan/rstan", ref = "experimental")

  # OR

  remotes::install_github("stan-dev/rstan/StanHeaders@experimental")
  remotes::install_github("stan-dev/rstan/rstan/rstan@experimental")
```

You may test it first before the patch.

**Comment by kn27** [comment] 2021-06-16 17:06
Dumb question, I ran 
`remotes::install_github("stan-dev/rstan", ref = "fix-attempt/v8-mem", subdir = "rstan/rstan")`

and got this error message which resulted in non-zero exit status
`g++: error: /home/keane/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a: No such file or directory`

Do I need to install the experimental branch first then the patch on top?

**Comment by hsbadr** [comment] 2021-06-16 18:07
> `g++: error: /home/keane/R/x86_64-pc-linux-gnu-library/3.6/rstan/lib//libStanServices.a: No such file or directory`

You need to install `StanHeaders` 1st before installing `rstan`. The instructions above include two lines in order: the 1st line installs `StanHeaders` while the 2nd installs `rstan`.

**Comment by kn27** [comment] 2021-06-16 20:21
Thank you! I was able to run `remotes::install_github("stan-dev/rstan/rstan/rstan@experimental")` successfully after install `StanHeaders`. However, I still got an error when trying to install the patch.

Again, I ran
`remotes::install_github("stan-dev/rstan", ref = "fix-attempt/v8-mem", subdir = "rstan/rstan")`

and got
```
chains.cpp:19:10: fatal error: stan/math/prim/mat/fun/mean.hpp: No such file or directory
   19 | #include <stan/math/prim/mat/fun/mean.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I'm a newbie here, so please forgive my ignorance. What did I miss?

**Comment by hsbadr** [comment] 2021-06-16 20:25
> chains.cpp:19:10: fatal error: stan/math/prim/mat/fun/mean.hpp: No such file or directory

It seems that you've conflicting `StanHeaders`. What the output of the following:
```r
packageVersion('StanHeaders')
packageVersion('rstan')
```
Both should return `2.27.0.9000`. If not, then you need to upgrade the package(s)

**Comment by kn27** [comment] 2021-06-16 20:35
Both return as expected 

```
> packageVersion('StanHeaders')
[1] ‘2.27.0.9000’
> packageVersion('rstan')
[1] ‘2.27.0.9000’
```
Do I need to uninstall `rstan` before installing the patch? I didn't do that when installing the experimental branch though, and it worked just fine.

**Comment by hsbadr** [comment] 2021-06-16 20:42
> remotes::install_github("stan-dev/rstan", ref = "fix-attempt/v8-mem", subdir = "rstan/rstan")

You're using the wrong branch, which is based on the old version. It should be `ref =  "fix/v8-mem"` and it isn't quite ready yet. When it's ready, it'll get merged into `experimental` branch.

**Comment by hsbadr** [comment] 2021-06-17 09:31
@cm421 Can you test the `experimental` branch? It should be fixed now. You might also need to call the garbage collection via `gc()`, if needed.

**Comment by cm421** [comment] 2021-06-17 17:03
Looks great to me!

Testing a local build of the `experimental` branch on both 
```
MacOS 11.4 with   R v4.0.5, and
Ubuntu 20.04 with R v3.6.3
```

I'm seeing the same drastically diminished memory usage as the `fix-attempt/v8-mem` feature branch. As an added bonus, on the `experimental` branch I'm no longer seeing the `CPP deprecated` warnings when calling `stanc_builder` either. Great work!

For what it's worth I still don't see any effect from calling `gc()`. After running
```
for (i in 1:500) {
  stanc_builder("../test_file.stan")
}
```
I can still see memory usage go up roughly 20MB, and calling `gc()` after that doesn't affect the memory reported in Activity Monitor. Not sure if that's expected behavior or not, but it doesn't seem like a huge issue to me since re-running that loop I sometimes see the memory usage drop back down roughly the same 20MB (without calling `gc()`), so looks like `rstan` is cleaning things up internally?

**Comment by SteveBronder** [comment] 2021-06-17 17:31
Nice!

> I can still see memory usage go up roughly 20MB, and calling gc() after that doesn't affect the memory reported in Activity Monitor. Not sure if that's expected behavior or not, but it doesn't seem like a huge issue to me since re-running that loop I sometimes see the memory usage drop back down roughly the same 20MB (without calling gc()), so looks like rstan is cleaning things up internally?

Is that after the for loop ends? As long as the memory is cleaned up at some point then I think we are okie-dokie

**Comment by hsbadr** [comment] 2021-06-17 17:42
I think the small memory fluctuations are ok, during/after running 500 calls to `stanc_builder()`. It could be a few temporary objects that are created by R or RStudio that will get cleaned up at some point.

I think we can close this issue now. Feel free to reopen a new issue if you run into this again.

**Closed as completed** 2021-06-17 18:30 UTC
