### ISSUE TITLE
After installing rstan, some error while executing function Stan.

### ISSUE THREAD

**Issue by bohyunshin** [stan-dev/rstan#794] opened 2020-07-14 10:36 UTC
#### Summary:
After installing rstan, some error occurred while executing function 'stan'.

#### Description:
After following instruction guide in rstan wiki, I successfully installed rstan and Rcpp and brought rstan package.

Actually, I got following message after `library(rstan)`
```
Loading required package: StanHeaders
Loading required package: ggplot2
rstan (Version 2.21.1, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
```
However, there seems to be no error, so I do not care of it.

#### Reproducible Steps:
```
library(rstan)
library(gdata)
x = cars$speed
y = cars$dist
N = nrow(cars)
stan_data = list(N=N, x=x, y=y)
write("// Stan model for simple linear regression

data {
 int < lower = 1 > N; // Sample size
 vector[N] x; // Predictor
 vector[N] y; // Outcome
}

parameters {
 real alpha; // Intercept
 real beta; // Slope (regression coefficients)
 real < lower = 0 > sigma; // Error SD
}

model {
 y ~ normal(alpha + x * beta , sigma);
}

generated quantities {
} // The posterior predictive distribution",

"stan_model1.stan")
stan_model1 = "stan_model1.stan"

fit <- stan(file = stan_model1, data = stan_data, warmup = 500, iter = 1000, chains = 4, cores = 2, thin = 1)
```

#### Current Output:
Following error occurred
```
sh: clang++ -mmacosx-version-min=10.13: command not found
The NEXT version of Stan will not be able to pre-process your Stan program.
Please open an issue at
 https://github.com/stan-dev/stanc3/issues 
if you can share or at least describe your Stan program. This will help ensure that Stan
continues to work on your Stan programs in the future. Thank you!
This message can be avoided by wrapping your function call inside suppressMessages().
Warning messages:
1: In system2(CXX, args = ARGS) : error in running command
2: In file.remove(c(unprocessed, processed)) :
  cannot remove file '/var/folders/dx/fvt_hjg96fs67jbf4fnjjckc0000gn/T//RtmpFoR15s/file248c5e6be22d.stan', reason 'No such file or directory'
```

#### Expected Output:
no idea because I'm newbie to Stan

#### RStan Version:
2.21.1

#### R Version:
R version 4.0.2 (2020-06-22)

#### Operating System:
macOS 10.15.5 Catalina

#### Conjecture
Because the error says **-mmacosx-version-min=10.13**, is this related to macOS? Because my OS is higher than 10.13, does this error occur?

Thank you for reading this issue!

**Comment by bohyunshin** [comment] 2020-07-14 15:52
solved this issue following the instructions in [here](https://github.com/stan-dev/rstan/issues/774).
That is, originally, I tried `remotes::install_github("stan-dev/rstan", ref = "develop", 
                        subdir = "rstan/rstan", build_opts = "")` as noted in rstan wiki [here](https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-source-on-a-Mac). However, after removing `build_opts` argument and installing with `remotes::install_github("stan-dev/rstan", ref = "develop", 
                        subdir = "rstan/rstan")`, I got no errors executing the above reproducible code.

Happy to solve the problem, but wonder why this little option makes big difference. Any one have an idea?

**Comment by SteveBronder** [comment] 2020-07-15 00:51
Thanks for filing an issue! I think this is a duplicate of #774 and should be discussed there. If you disagree feel free to reopen the issue.

**Closed as completed by SteveBronder** 2020-07-15 00:51 UTC
