### ISSUE TITLE
extract default option has permuted=TRUE

### ISSUE THREAD

**Issue by leoduan** [stan-dev/rstan#423] opened 2017-06-21 19:03 UTC
#### Summary:
The default option of having permuted=TRUE in **extract** function is very misleading. 

#### Description:
When doing convergence diagnostics / assessing convergence rate, permutation of the Markov chain gives a false impression that the chain converges rapidly.

Most users wouldn't notice (myself included until today) that this option is on by default. I strongly urge you to turn it off in the next update.

**Comment by bgoodri** [comment] 2017-06-21 19:08
Take it up with Andrew.

**Comment by bob-carpenter** [comment] 2017-06-21 19:16
@bgoodri --- weren't you going to change that in the future?  Are you going to wait for RStan 3?  @andrewgelman has already said it's OK with him.

**Comment by bgoodri** [comment] 2017-06-21 19:31
We are definitely changing it ASAP. The question is how soon.

**Comment by ariddell** [comment] 2017-06-21 20:31
Duplicate of #345

**Comment by bob-carpenter** [comment] 2017-06-21 21:18
Given that it's a duplicate of #345, I'm closing.

**Closed as completed by bob-carpenter** 2017-06-21 21:18 UTC
