### ISSUE TITLE
Error in loo(stanfit, moment_match=TRUE)

### ISSUE THREAD

**Issue by mcol** [stan-dev/rstan#852] opened 2020-09-15 13:15 UTC
#### Summary:
The following fails
```r
> rstan::loo(lp.fit, moment_match=TRUE)
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In parallel::mclapply(X = I, mc.cores = cores, FUN = function(i) loo_moment_match_i_fun(i)) :
  scheduled cores 8, 3, 1 encountered errors in user code, all values of the jobs will be affected
````

#### Description:
Calling `loo` on a stanfit object (for a model that contains a `log_lik` term) with moment matching fails as shown above. Traceback is the following:
```r
> traceback()
5: loo::loo_moment_match.default(x = x, loo = loo, post_draws = post_draws_stanfit,
       log_lik_i = log_lik_i_stanfit, unconstrain_pars = unconstrain_pars_stanfit,
       log_prob_upars = log_prob_upars_stanfit, log_lik_i_upars = log_lik_i_upars_stanfit,
       ...)
4: loo_moment_match.stanfit(x, loo = loo, chain_id = chain_id, k_threshold = k_threshold,
       cores = cores, parameter_name = pars, ...)
3: .local(x, ...)
2: rstan::loo(lp.fit, moment_match = TRUE)
1: rstan::loo(lp.fit, moment_match = TRUE)
```

If it helps, here's the output without moment matching:
```r
> loo(lp.fit)

Computed from 1200 by 11 log-likelihood matrix

         Estimate    SE
elpd_loo  -2823.1 339.8
p_loo        31.2   4.3
looic      5646.3 679.5
------
Monte Carlo SE of elpd_loo is NA.

Pareto k diagnostic values:
                         Count Pct.    Min. n_eff
(-Inf, 0.5]   (good)     0      0.0%   <NA>
 (0.5, 0.7]   (ok)       1      9.1%   44
   (0.7, 1]   (bad)      6     54.5%   13
   (1, Inf)   (very bad) 4     36.4%   4
See help('pareto-k-diagnostic') for details.
Warning message:
Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.
```

#### Reproducible Steps:
I can send the failing stanfit object if necessary

#### RStan Version:
RStan version: 2.21.2
loo version: 2.3.1

#### R Version:
R version 3.6.0 (2019-04-26)

#### Operating System:
Linux Ubuntu 18.04.4 LTS

**Comment by jgabry** [comment] 2020-09-15 19:34
> ```r
> Error: $ operator is invalid for atomic vectors
> In addition: Warning message:
> In parallel::mclapply(X = I, mc.cores = cores, FUN = function(i) loo_moment_match_i_fun(i)) :
>   scheduled cores 8, 3, 1 encountered errors in user code, all values of the jobs will be affected
> ```

Hmm, I haven't seen that particular error from running moment matching loo. @topipa or @paul-buerkner have you seen this? Any ideas? 


> I can send the failing stanfit object if necessary

Yeah that might help debug this. Or the Stan program and some data to run it would be fine too.

**Comment by topipa** [comment] 2020-09-16 04:17
Thank you for reporting this. I have not encountered this kind of error before. The error is quite generic so nothing specific comes to my mind off the top of my head. Did you encounter this also when using 1 core, or only when using multiple cores?

If you can send a reproducible example, that would be really helpful!

**Comment by mcol** [comment] 2020-09-16 10:54
I've run with `cores=1`, and this shows the following:
```r
Error in validate_ll(log_ratios) : All input values must be finite.
> traceback()
16: stop("All input values must be finite.")
15: validate_ll(log_ratios)
14: importance_sampling.matrix(log_ratios, r_eff = r_eff, cores = 1,
        method = method)
13: importance_sampling.default(lwi_half, method = is_method, r_eff = r_eff_i,
        cores = cores)
12: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
11: suppressWarnings(importance_sampling.default(lwi_half, method = is_method,
        r_eff = r_eff_i, cores = cores))
10: loo_moment_match_split(x, upars, cov, total_shift, total_scaling,
        total_mapping, i, log_prob_upars = log_prob_upars, log_lik_i_upars = log_lik_i_upars,
        cores = 1, r_eff_i = r_eff_i, is_method = is_method, ...)
9: loo_moment_match_i(i = i, x = x, log_lik_i = log_lik_i, unconstrain_pars = unconstrain_pars,
       log_prob_upars = log_prob_upars, log_lik_i_upars = log_lik_i_upars,
       max_iters = max_iters, k_threshold = k_threshold, split = split,
       cov = cov, N = N, S = S, upars = upars, orig_log_prob = orig_log_prob,
       k = ks[i], is_method = is_method, npars = npars, ...)
8: loo_moment_match_i_fun(i)
7: FUN(X[[i]], ...)
6: lapply(X = I, FUN = function(i) loo_moment_match_i_fun(i))
5: loo::loo_moment_match.default(x = x, loo = loo, post_draws = post_draws_stanfit,
       log_lik_i = log_lik_i_stanfit, unconstrain_pars = unconstrain_pars_stanfit,
       log_prob_upars = log_prob_upars_stanfit, log_lik_i_upars = log_lik_i_upars_stanfit,
       ...)
4: loo_moment_match.stanfit(x, loo = loo, chain_id = chain_id, k_threshold = k_threshold,
       cores = cores, parameter_name = pars, ...)
3: .local(x, ...)
2: rstan::loo(lp.fit, moment_match = TRUE, cores = 1)
1: rstan::loo(lp.fit, moment_match = TRUE, cores = 1)
```

After some debugging, I see that in `loo_moment_match_split` the following expression generates some infinities:
```r
  # compute weights
  lwi_half <- -log_liki_half + log_prob_half_trans -
    (log_prob_half_trans +
       log(1 + exp(log_prob_half_trans_inv - log(prod(total_scaling)) -
                     log(det(total_mapping)) - log_prob_half_trans)))
```
as some elements of `log_prob_half_trans_inv - log_prob_half_trans_inv` is very large (over 1000), while the log terms on total_scaling and total_mapping evaluate to zero.

**Comment by topipa** [comment] 2020-09-17 05:55
Thank you for the additional details! Now I know what the cause is. It is because of using a logarithmic identity for `log(a + c)` which increases numerical stability, but fails if `log_prob_half_trans` << `log_prob_half_trans_inv - log(prod(total_scaling)) - log(det(total_mapping)` . I will make a fix for this by adding a check that uses another logarithmic identity if this is the case.

**Comment by jgabry** [comment] 2020-09-17 17:20
Now that https://github.com/stan-dev/loo/pull/153 exists I think we can close this because the issue is in the loo package and not rstan. Thanks again @mcol for reporting this and @topipa for looking into it!

**Closed as completed by jgabry** 2020-09-17 17:20 UTC
