### ISSUE TITLE
Loop of regressions causes "all connections are in use" error

### ISSUE THREAD

**Issue by jmh530** [stan-dev/rstan#230] opened 2015-11-16 23:25 UTC
Title:
Loop of regressions causes "all connections are in use" error

Version: 2.8
# define STAN_MAJOR 2
# define STAN_MINOR 8
# define STAN_PATCH 0

(The CONTRIBUTING.md should probably make clear that rstan's version file is located in StanHeaders' include folder)

Description:
I am finding that when I run a large number of Stan regressions in a loop, I am getting error messages, such as 

```
<simpleError in textConnection("rval", "w", local = TRUE): all connections are in use>
```

I am noticing that I start getting them after about 30 Stan regressions in loops when using 4 chains and about 120 regressions with only one chain. 

There is likely a limit in R for number of connections. I know I can view the connections with showConnections(). I don't recall this being an issue in some earlier versions of Stan. I believe it is possible to close the connections. I could probably save the data I need and then figure out how to close them, but I figure it should be brought to somebody's attention as well.

Steps:
I put the code for two files below. The r file creates some data and fits a mean and standard deviation in each time period. This was the simplest way I could illustrate the issue. 

test_connection_bug.r

```
library(tidyr)
library(dplyr)
library(rstan)
rstan_options(auto_write = TRUE)

# Set directory
wd <- "C:/ProgrammingFiles/StanFiles/Test_Connection_Bug"
setwd(wd)

# Some constants
N <- 100
T <- 200
NT <- N * T

N_iter <- 250
N_chain <- 4

mu_e <- 1
sd_e <- 10

mu_n <- rnorm(N, 0, 0.2)

# Creating y
y <- matrix(rnorm(NT, mu_e, sd_e), T, N)
y <- y + matrix(kronecker(mu_n, rep(1, T)), T, N)

colnames(y) <- 1:N
rownames(y) <- 1:T

# Creating data frame panel
df_1 <- data.frame(time_id=seq(1, T), firm_id=y)

df_1 <- df_1 %>%
        gather(firm_id, val, -time_id) %>%
        separate(firm_id, into = c("val1", "val2", "firm_id")) %>%
        select(-val1, -val2) %>%
        mutate(id=1:NT) %>%
        mutate(firm_id = as.integer(firm_id)) %>%
        arrange(time_id, firm_id)

# Do initial Stan for compiled version
i <- 1
df_i <- df_1 %>%
            filter(time_id == i)
stan_data_i <- list(N_obs = length(df_i$val), y=df_i$val)
fit_0 <- stan(file = 'mean.stan', data = stan_data_i, verbose = FALSE,
              iter = 50, chains = 1)

# Run Stan in Loop
for (i in 1:T)
{
    df_i <- df_1 %>%
                filter(time_id == i)
    stan_data_i <- list(N_obs = length(df_i$val), y=df_i$val)
    fit <- stan(fit=fit_0, data = stan_data_i, verbose = FALSE,
                iter = N_iter, chains = N_chain)
}
```

mean.stan

```
data {
    int<lower=0> N_obs;
    vector[N_obs] y;
}
parameters {
    real mu;

    real<lower=0> sigma_e;
}
model {
    y ~ normal(mu, sigma_e);
}
```

Output:
The typical output is something like:
    Error in file(file, "r") : all connections are in use
    simpleError in textConnection("rval", "w", local = TRUE): all connections are in use

That last line has < > on the ends, but it causes problems with the http formatting. The last line will also appear multiple times, likely due to the loop continuing running. 

Expected Output:
The expected output would be that the loop runs without any problems.

**Comment by maverickg** [comment] 2015-11-17 01:44
duplicate of #225 and #219 

rstan's version is printed out when rstan is loaded, see an example below of a version built from source (that is, not from cran):

```
> library(rstan)
Loading required package: Rcpp
Loading required package: ggplot2
rstan (Version 2.8.1, packaged: 2015-11-01 18:42:31 UTC, GitRev: 1c7632957441)
For execution on a local, multicore CPU with excess RAM we recommend calling
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

And the version of stan packaged in rstan can be obtained by function `stan_version`.

```
> stan_version()
[1] "2.8.0"
```

**Comment by jmh530** [comment] 2015-11-17 02:07
I only searched for the existing issues. Sorry for the duplicate. Feel free to close.

**Closed as completed** 2015-11-17 19:13 UTC
