### ISSUE TITLE
Rstan doesn't sample data after compiling

### ISSUE THREAD

**Issue by rentzb** [stan-dev/rstan#454] opened 2017-09-29 19:13 UTC
#### Summary:
After compiling stan models,  I get an error message at the beginning of sampling from the sampler, which then quits, returning a stan object with zero samples.

#### Description:
Whenever I run a Stan model, I get the following message when sampling begins:
`[1] "Error in sampler$call_sampler(args_list[[i]]) c++ exception (unknown
reason)"`
`error occurred during calling the sampler; sampling not done`
The sampling process then terminates and returns an object with no samples. I reinstalled rstan, Rcpp, and brms following the directions on the rstan page. I also tried installing them from source and still the sample problem. I initially posted this to the brms page, but they redirected me here. I also have XCode installed. 

#### Reproducible Steps:
`library(ordinal)`
`library(brms)`
`data(soup)`
`agemdl <- brm(SURENESS ~ PROD + (1|RESP), data = soup, family=cumulative("logit"), threshold="flexible",chains=1)`

#### RStan Version:
2.16.2
#### R Version:
3.4.1

#### Operating System:
MacOS 10.12.6

#### Compiler versions
clang 8.1.0
g++ 4.2.1
gcc 7.2.0 (via homebrew)

**Comment by bgoodri** [comment] 2017-09-29 23:51
Can you post the output of

rstan:::get_CXX()

?

**Comment by rentzb** [comment] 2017-09-30 00:13
"clang++ -arch x86_64 -ftemplate-depth-256"

**Comment by bgoodri** [comment] 2017-09-30 00:29
We have a fix for this on GitHub. Do

devtools::install_github("stan-dev/rstan", ref = "develop", subdir =
"rstan/rstan")

**Comment by rentzb** [comment] 2017-09-30 01:30
I just reinstalled rstan using that code. Still giving the same error.

**Comment by bgoodri** [comment] 2017-09-30 02:18
What happens if you follow
http://discourse.mc-stan.org/t/error-in-rstan-2-16-2-after-upgrading-to-r-3-4-1-with-clang-4-0-0/1893/19?u=bgoodri

**Comment by rentzb** [comment] 2017-09-30 02:41
My Makevars file had the following lines:
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib

I removed them and restarted R and the model works fine now

**Comment by bgoodri** [comment] 2017-09-30 02:54
Yeah, but it is supposed to work with those lines when installed from
GitHub.

**Comment by DanOvando** [comment] 2017-10-31 19:05
FYI, I encountered a similar problem as @rentzb: "Error in sampler$call_sampler(args_list[[i]]) c++ exception (unknown reason)". It doesn't happen whenever I call `rstan`, e.g. the examples from `?stan` work correctly, and my model compiles, but after a few iterations I get the above error. 

After installing `rstan` from Github still had the "Error in sampler$call_sampler(args_list[[i]]) c++ exception (unknown reason)" until I manually removed 

CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib

from my Makevars file, at which point the problem went away and my model continued running

I can't put a reproducible example up since the model in question requires a large amount of data that I can't share (and the problem doesn't pop up in simpler models), and since removing those lines from Makevars seemed to work I'm not looking for a response, but thought you might like to know that this problem cropped up on my end as well. 

Thanks

Dan

RStan Version:

2.17.1

R Version:

3.4.2

Operating System:

MacOS 10.12.6

Compiler versions

clang 9.0.0
g++ 4.2.1
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by bgoodri** [comment] 2017-10-31 19:08
The data don't matter. With RStan < 2.17.x, the models usually don't work
with the clang4 compiler from the AT&T website. You can install what will
become RStan 2.17 from GitHub via

devtools::install_github("stan-dev/rstan", ref = "develop", subdir =
"rstan/rstan")

which has some hacks to get it to work with clang4.

**Comment by DanOvando** [comment] 2017-10-31 19:26
Thanks @bgoodri. per your earlier comment, 

"Yeah, but it is supposed to work with those lines when installed fromGitHub."

 I thought you might like to know that I found the same issue as @rentzb in that even after installing the dev version of rstan per  
`devtools::install_github("stan-dev/rstan", ref = "develop", subdir =
"rstan/rstan")`, restarting everything etc, my model only worked after I then removed those lines manually from Makevars. Working great now though!

**Comment by bgoodri** [comment] 2017-11-10 21:44
@rentzb Do you have any idea why `rstan:::get_CXX()` for you only returns `clang++ ...` rather than `/usr/local/clang4/bin/clang++ ...`. The R code on GitHub is grepping for `"clang4"` to trigger the workaround which is not found in your case.

**Comment by cimentadaj** [comment] 2018-08-09 17:49
Was getting the same error and fixed this with the answers from @DanOvando and @rentzb. I think this might be due to the fact that I had two `CC` and `CCX` vars where one pointed to `clang4` and the other to `clang`. I commented out the one pointing to `clang4` and it was fixed.

**Comment by davidmanheim** [comment] 2019-03-25 09:15
This looks like it should have been / was fixed in RStan 2.17 - can it be closed?

**Closed as completed** 2019-03-25 14:21 UTC
