### ISSUE TITLE
de/serialization issues

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/rstan#373] opened 2016-12-21 17:34 UTC
_From @wds15 on December 21, 2016 14:41_

#### Summary:
When using rstan 2.13 stan_rdump to serialize arrays with zero size , then these cannot be read with cmdstan 2.13

#### Description:
Serializing with stan_rdump and starting a cmdstan run does not work any more if the arrays has size zero. This used to work with rstan 2.12 and cmdstand 2.12.

This releated to the issue rstan#371 .

#### Reproducible Steps:
serialized data with rstan 2.13 which does not work with cmdstan 2.13:
```
N <- 0
y <- 
structure(integer(0), 
.Dim = c(0))
```

this data works with cmdstan 2.13 and was generated with rstan 2.12:
```
N <- 0
y <- 
structure(c(),
.Dim = c(0))
```

Here is a dummy Stan program:
```
data {
  int N;
  int y[N];
}
parameters {
  real mu;
}
model {
  target += normal_lpdf(mu|0, 1);
}
```

#### Current Output:
cmdstan fails to run

#### Expected Output:
Error from cmdstan:
```
[weberse2@node04:~/work/stan/misc] ./stan_int_bug sample data file=notok.R

Exception: data y value  beyond int range
Diagnostic information: 
stan_2.13.1/src/stan/io/dump.hpp(518): Throw in function bool stan::io::dump_reader::next()
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::invalid_argument> >
std::exception::what: data y value  beyond int range
```

#### cmdstan Stan Version:
2.13.1

#### Operating System:
RHEL 6.7

_Copied from original issue: stan-dev/stan#2179_

**Comment by maverickg** [comment] 2016-12-22 04:09
duplicate of #371.

**Closed as completed by maverickg** 2016-12-22 04:09 UTC

**Comment by syclik** [comment] 2016-12-22 13:56
The reason Bob moved it to establish is because this broke functional behavior that should have between tested. Could we leave this open until either the Stan repo us fixed or the RStan repo has tests to prevent breaking backwards compatibility?
