### ISSUE TITLE
rstan 2.8.2 - bug in traceplot under Windows

### ISSUE THREAD

**Issue by Radibor** [stan-dev/rstan#247] opened 2015-12-30 19:10 UTC
Hello,

Straight from the help:
library(rstan) 
fit <- stan(model_code = "parameters {real y;} model {y ~ normal(0,1);}") 
traceplot(fit)

Error in if (debug) { : argument is of length zero

I tried to debug traceplot. The issue is probably due to thm in stan_trace

thm <- .rstanvis_defaults$theme

If I don't use thm in

  graph <-
    base +
    geom_path(...) +
    scale_color_manual(values = clrs) +
    labs(x="",y="") # +
   # thm

then no error occurs, and a plot is created that looks alright to me.

BTW, the error is Windows-specific. traceplot works fine for me under Linux.

Regards
Wolfgang

R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.8.2   ggplot2_2.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      codetools_0.2-14 digest_0.6.8     grid_3.2.3       plyr_1.8.3       gtable_0.1.2     stats4_3.2.3  
 [8] scales_0.3.0     rstudioapi_0.4.0 labeling_0.3     tools_3.2.3      munsell_0.4.2    parallel_3.2.3   inline_0.3.14  
[15] colorspace_1.2-6 gridExtra_2.0.0

**Comment by jgabry** [comment] 2015-12-30 21:59
Thanks for reporting. This looks like the same issue as #222 -- in particular see the first comment by @jrnold -- and is related to @hadley's recent ggplot2 update to version 2.0.0. For some reason we still haven't figured out, the text elements in the theme are missing `debug`, which was just added as an argument to `element_text` in version 2.0.0. This is why you're seeing `Error in if (debug)`. Despite version 2.0.0 being loaded, when the theme is created it is sometimes only valid for ggplot2 < 2.0.0. Oddly, this seems to happen occasionally and then disappear mysteriously.

Are you by any chance using a saved workspace that was created before the update?

**Comment by Radibor** [comment] 2015-12-30 23:29
Thanks for your quick reply. No, I'm not using a saved workspace. I see the issue has already been reported and is being investigated.

BTW, like with jrnold, rstan:::.rstanvis_defaults$theme$text also gives me a List of 8 instead of 10.

**Comment by hoxo-m** [comment] 2016-01-01 14:38
It has also occurred in my Windows and Mac.
For the time being, I'm going to resolve it as follows:

``` r
devtools::install_github("hoxo-m/fixer")
fixer::fix_params_persist(ggplot2:::titleGrob(debug = FALSE))
```

**Comment by Radibor** [comment] 2016-01-02 16:51
Thank you for making your fix available. I installed it, but unfortunately I'm still getting that error.

**Comment by bob-carpenter** [comment] 2016-01-05 06:31
I'm now getting this error with new RStan 2.8.2 install.  

How would I check whether I'm using an old workspace or not?  I'm using R in a terminal.

**Comment by jgabry** [comment] 2016-01-05 09:18
Most likely you're not using an old workspace. I think you'd have to have
saved one and then loaded it when starting up R, so it would have required
some action on your part.

This ggplot2 error is really annoying. And I haven't been able to replicate
it on my own computer so it's particularly hard to debug. I'm hoping that
installing rstan 2.9 (Ben's planning a release soon) will fix it since I've
tried to manually set some ggplot theme parameters that weren't getting set
by default, but I'm still trying to reproduce the error so it's quite
frustrating.

I'm about to get on a flight back to NYC, but when I'm back I'll try to
reproduce it on a few other systems and hopefully I'll have more luck.

**Comment by bob-carpenter** [comment] 2016-01-05 16:32
Well, you'll have my machine to work with when you get back.
- Bob

**Comment by jgabry** [comment] 2016-01-09 04:44
This should be fixed now with the release of version 2.9.

**Closed as completed by jgabry** 2016-01-09 04:44 UTC
Labels: bug

**Comment by Radibor** [comment] 2016-01-10 16:34
Thanks a lot! It's working for me now.

**Comment by hoxo-m** [comment] 2016-01-11 02:42
By updating, It's working on my PC too. Thank you!

**Comment by jgabry** [comment] 2016-01-11 03:20
Glad it's working. Thanks for letting us know.

**Comment by isamuelgh** [comment] 2017-02-01 00:29
Hi,
I have rstan 2.14.1 installed and when i run traceplot(fit, pars = c('beta'), inc_warmup = FALSE) I get this error message below. Any ideas how to fix this?
Error in `[.unit`(padding, 4) : index out of bounds ('unit' subsetting)

**Comment by jgabry** [comment] 2017-02-01 01:48
@isamuelgh Does the same thing happen if you replace `traceplot` with `stan_trace`?

**Comment by jgabry** [comment] 2017-02-01 01:50
If possible can you also set `options(error = recover)`, then trigger the error and share the output? Thanks!

**Comment by isamuelgh** [comment] 2017-02-01 01:59
Error in `[.unit`(padding, 4) : index out of bounds ('unit' subsetting)

Enter a frame number, or 0 to exit   
I don't know if this is what you request.

> traceplot(fit, pars = c('beta'), inc_warmup = FALSE)
Error in `[.unit`(padding, 4) : index out of bounds ('unit' subsetting)
 1: function (x, ...) 
UseMethod("print")(x)
 2: print.ggplot(x)
 3: ggplot_gtable(data)
 4: build_guides(plot$scales, plot$layers, plot$mapping, position, theme, plot$guides, plo
 5: guides_gengrob(gdefs, theme)
 6: lapply(gdefs, guide_gengrob, theme)
 7: FUN(X[[i]], ...)
 8: guide_gengrob.legend(X[[i]], ...)
 9: padding[4]
10: `[.unit`(padding, 4)

**Comment by isamuelgh** [comment] 2017-02-01 02:03
Yes, the same error occurs when i use stan_trace().

**Comment by jgabry** [comment] 2017-02-01 02:19
Thanks. I'm not sure what the problem is. I'm not able to reproduce this error. Which version of the ggplot2 package do you have? Also, do you get the same error if you use one of the Stan demo models? For example:

```r
fit <- stan_demo("eight_schools")
stan_trace(fit, pars = "theta")
```
